### ISSUE TITLE
Big Picture segfault

### ISSUE THREAD

**Issue by MayeulC** [ValveSoftware/steam-for-linux#2448]
Hello,

I Have a segmentation fault when I try to launch big picture mode.
I have an ATI Radeon HD 4850 with 13.1 legacy drivers.

Terminal output (I tried to translate) : 

```
Installing breakpad exception handler for appid(steam)/version(1368229716_client)
[xcb] Unknown sequence number while appending request
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
steam: ../../src/xcb_io.c :160 : append_pending_request:  Assertion « !xcb_xlib_unknown_seq_number » failed.
[2013-05-11 13:37:00] Startup - updater built May 10 2013 14:57:30
[2013-05-11 13:37:00] Opted in to client beta 'publicbeta' via beta file
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2013-05-11 13:37:00] Checking for update on startup
[2013-05-11 13:37:00] Checking for updates...
[2013-05-11 13:37:02] Nothing to do
[2013-05-11 13:37:02] Checking installation...
[2013-05-11 13:37:02] Verification complete
/home/mayeul/.local/share/Steam/steam.sh : line 704 : 15366 Segmentation fault  $STEAM_DEBUGGER "$STEAMROOT/$PLATFORM/$STEAMEXE" "$@"
```

Backtrace : 

```
Program received signal SIGSEGV, Segmentation fault.
0xf7ee0224 in _XGetRequest () from /home/mayeul/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libX11.so.6
(gdb) bt
#0  0xf7ee0224 in _XGetRequest () from /home/mayeul/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libX11.so.6
#1  0xf7ed2b8d in XQueryExtension () from /home/mayeul/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libX11.so.6
#2  0xf7ec693c in XInitExtension () from /home/mayeul/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libX11.so.6
#3  0xf7926794 in XextAddDisplay () from /home/mayeul/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libXext.so.6
#4  0xf79a5fd8 in ?? () from /usr/lib/libGL.so.1
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

I can provide you more information if you would like.

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant.
