### ISSUE TITLE
Kubuntu 13.10 64bit environment, segfault on start

### ISSUE THREAD

**Issue by HenAlm** [ValveSoftware/steam-for-linux#3180]
I've installed a fresh 64but version of kubuntu 13.10. It is running nvidia binary drivers 331.49. It is a HP zbook 15 laptop. However steam does not start. I get following into the terminal with starting:

```
$ steam
Running Steam on ubuntu 13.10 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(0_client)
/home/hena/.local/share/Steam/steam.sh: line 755:  5025 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$PLATFORM/$STEAMEXE" "$@"
mv: cannot stat ‘/home/hena/.steam/registry.vdf’: No such file or directory
Installing bootstrap /home/hena/.local/share/Steam/bootstrap.tar.xz
Reset complete!
Restarting Steam by request...
Running Steam on ubuntu 13.10 64-bit
STEAM_RUNTIME has been set by the user to: /home/hena/.local/share/Steam/ubuntu12_32/steam-runtime
Installing breakpad exception handler for appid(steam)/version(0_client)
/home/hena/.local/share/Steam/steam.sh: line 755:  5152 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$PLATFORM/$STEAMEXE" "$@"
```

Using gdb I can get a following backtrace

```
$ DEBUGGER="gdb" steam
Running Steam on ubuntu 13.10 64-bit
STEAM_RUNTIME is enabled automatically
GNU gdb (GDB) 7.6.1-ubuntu
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /home/hena/.local/share/Steam/ubuntu12_32/steam...(no debugging symbols found)...done.
(gdb) run
Starting program: /home/hena/.local/share/Steam/ubuntu12_32/steam 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Installing breakpad exception handler for appid(steam)/version(0_client)

Program received signal SIGSEGV, Segmentation fault.
0x00000000 in ?? ()
(gdb) bt
#0  0x00000000 in ?? ()
#1  0xf7d43dd8 in pthread_once () from /lib/i386-linux-gnu/libpthread.so.0
#2  0xf7310d56 in ?? () from /usr/lib32/libGL.so.1
#3  0xf7311822 in ?? () from /usr/lib32/libGL.so.1
#4  0xf7feb1c5 in ?? () from /lib/ld-linux.so.2
#5  0xf7feb2ec in ?? () from /lib/ld-linux.so.2
#6  0xf7fef2c6 in ?? () from /lib/ld-linux.so.2
#7  0xf7feb04e in ?? () from /lib/ld-linux.so.2
#8  0xf7feeb04 in ?? () from /lib/ld-linux.so.2
#9  0xf7e39cce in ?? () from /lib/i386-linux-gnu/libdl.so.2
#10 0xf7feb04e in ?? () from /lib/ld-linux.so.2
#11 0xf7e3a422 in ?? () from /lib/i386-linux-gnu/libdl.so.2
#12 0xf7e39d87 in dlopen () from /lib/i386-linux-gnu/libdl.so.2
#13 0x08079470 in LoadGlFuncs(void**) ()
#14 0x0807e624 in CBaseLinuxUpdateUI::BaseCreateWindow() ()
#15 0x0807f014 in CXWindowsUpdateUI::BCreateWindow() ()
#16 0x080501d4 in main ()
(gdb)
```

Any ideas on what to do here?
Thanks

**Comment by kisak-valve** [comment]
Closing as this appears to have been a system configuration issue with the 32 bit OpenGL driver.
