### ISSUE TITLE
Natural Selection 2 Crashes during caching

### ISSUE THREAD

**Issue by GavinMendelGleason** [ValveSoftware/steam-for-linux#3184]
I'm running Natural Selection 2 on ubuntu 13.10 and it crashes consistently on either shader loading or during pre-caching on the optimisation stage.  I just bought the game and have never been able to play so it would be nice to know of a workaround. 

Sysinfo: 

```
System information report, generated by Sysinfo: 03/03/2014 18:39:24
http://sourceforge.net/projects/gsysinfo

SYSTEM INFORMATION
    Running Ubuntu Linux, the Ubuntu 13.10 (saucy) release.
    GNOME: 3.8.4 (Ubuntu 2013-12-05)
    Kernel version: 3.11.0-17-generic (#31-Ubuntu SMP Mon Feb 3 21:53:31 UTC 2014)
    GCC: 4.8 (i686-linux-gnu)
    Xorg: 1.14.5 (17 December 2013  10:03:52AM) (17 December 2013  10:03:52AM)
    Hostname: rowan-Latitude-E5520
    Uptime: 0 days 16 h 36 min

CPU INFORMATION
    GenuineIntel, Intel(R) Core(TM) i3-2350M CPU @ 2.30GHz
    Number of CPUs: 4
    CPU clock currently at 800.000 MHz with 3072 KB cache
    Numbering: family(6) model(42) stepping(7)
    Bogomips: 4589.73
    Flags: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe nx rdtscp lm constant_tsc arch_perfmon pebs bts xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer xsave avx lahf_lm arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid

MEMORY INFORMATION
    Total memory: 7989 MB
    Total swap: 8086 MB

STORAGE INFORMATION
    SCSI device -  scsi0
        Vendor:  ATA      
        Model:  ST9500423AS      
    SCSI device -  scsi1
        Vendor:  TSSTcorp 
        Model:  DVD+-RW SN-208BB 

HARDWARE INFORMATION
MOTHERBOARD
    Host bridge
        Intel Corporation 2nd Generation Core Processor Family DRAM Controller (rev 09)
        Subsystem: Dell Device 049a
    PCI bridge(s)
        Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 1 (rev b4) (prog-if 00 [Normal decode])
        Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 2 (rev b4) (prog-if 00 [Normal decode])
        Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 3 (rev b4) (prog-if 00 [Normal decode])
        Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 6 (rev b4) (prog-if 00 [Normal decode])
        Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 7 (rev b4) (prog-if 00 [Normal decode])
    ISA bridge
        Intel Corporation HM65 Express Chipset Family LPC Controller (rev 04)
        Subsystem: Dell Device 049a

GRAPHIC CARD
    VGA controller
        Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09) (prog-if 00 [VGA controller])
        Subsystem: Dell Device 049a

SOUND CARD
    Multimedia controller
        Intel Corporation 6 Series/C200 Series Chipset Family High Definition Audio Controller (rev 04)
        Subsystem: Dell Device 049a

NETWORK
    Network controller
        Broadcom Corporation BCM43228 802.11a/b/g/n
        Subsystem: Dell Wireless 1530 Half-size Mini PCIe Card
    Ethernet controller
        Broadcom Corporation NetXtreme BCM5761 Gigabit Ethernet PCIe (rev 10)
        Subsystem: Dell Device 049a
```

Backtrace: 

```
#0  __memcpy_ssse3_rep ()
    at ../sysdeps/i386/i686/multiarch/memcpy-ssse3-rep.S:148
#1  0xa0b78c73 in ?? ()
   from /usr/lib/i386-linux-gnu/alsa-lib/libasound_module_pcm_pulse.so
#2  0xb26dda35 in ?? ()
   from /home/rowan/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libasound.so.2
#3  0xb2699642 in ?? ()
   from /home/rowan/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libasound.so.2
#4  0xb26ddbfa in ?? ()
   from /home/rowan/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libasound.so.2
#5  0xa0a42cb8 in snd_pcm_readi () from /usr/lib/i386-linux-gnu/libasound.so
#6  0xb68fed44 in ?? ()
   from /home/rowan/.local/share/Steam/SteamApps/common/Natural Selection 2/libfmodex.so
#7  0xb68f6c55 in ?? ()
   from /home/rowan/.local/share/Steam/SteamApps/common/Natural Selection 2/libfmodex.so
#8  0xb3a2dd78 in start_thread (arg=0x97609b40) at pthread_create.c:311
#9  0xb380f01e in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:131
```

**Comment by kisak-valve** [comment]
Hello @GavinMendelGleason, if you are still experiencing issues with this game on an up to date system, please contact the game's devs.
