### ISSUE TITLE
Steam Beta Overlay segfaults on Archlinux

### ISSUE THREAD

**Issue by ChristophHaag** [ValveSoftware/steam-for-linux#3427]
Build from Aug 9.

Yes, there are a few other issues already but they don't seem to exactly match.

I have deleted libgcc_s.so.1 from steam runtime because it was too old to support newly compiled mesa drivers on Archlinux.

I have deleted all libxcb stuff from steam runtime because it was mentioned here: https://github.com/ValveSoftware/steam-for-linux/issues/3093#issuecomment-37022796

This one seemed to be the fault of something else, bumblebee? https://github.com/ValveSoftware/steam-for-linux/issues/3199#issuecomment-47330106

I'm sure you have received a lot of crash reports from me already from my playing around.

Looks like this in dmesg:

```
[171738.917145] gameoverlayui[17811]: segfault at 0 ip 00000000f7024b8b sp 00000000ffb46400 error 4 in gameoverlayui.so[f6ee3000+45f000]
[171779.459873] gameoverlayui[18033]: segfault at 0 ip 00000000f7060b8b sp 00000000ffd15760 error 4 in gameoverlayui.so[f6f1f000+45f000]
[171874.940072] gameoverlayui[18271]: segfault at 0 ip 00000000f6fe4b8b sp 00000000ffce0c10 error 4 in gameoverlayui.so[f6ea3000+45f000]
[172258.950463] gameoverlayui[18760]: segfault at 0 ip 00000000f704db8b sp 00000000ff9c59b0 error 4 in gameoverlayui.so[f6f0c000+45f000]
[173146.801508] gameoverlayui[20709]: segfault at 0 ip 00000000f6ff0b8b sp 00000000ffec5530 error 4 in gameoverlayui.so[f6eaf000+45f000]
```

Happens on mesa intel graphics and offloaded to mesa radeonsi graphics in all combinations with and without dri3.

There are core files in ~/.local/share/Steam/ubuntu12_32/ that belong to the overlay but there's really not much information without debugging symbols:

```
gdb ~/.local/share/Steam/ubuntu12_32/gameoverlayui ~/.local/share/Steam/ubuntu12_32/core.20709
[...]
Reading symbols from /home/chris/.local/share/Steam/ubuntu12_32/gameoverlayui...(no debugging symbols found)...done.
[New LWP 20709]

warning: Could not load shared library symbols for linux-gate.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `/home/chris/.local/share/Steam/ubuntu12_32/gameoverlayui -pid 20707 -manuallycl'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0xf6ff0b8b in ?? () from /home/chris/.local/share/Steam/ubuntu12_32/gameoverlayui.so
(gdb) bt
#0  0xf6ff0b8b in ?? () from /home/chris/.local/share/Steam/ubuntu12_32/gameoverlayui.so
#1  0xf6ff4585 in ?? () from /home/chris/.local/share/Steam/ubuntu12_32/gameoverlayui.so
#2  0xf6ff49ae in ?? () from /home/chris/.local/share/Steam/ubuntu12_32/gameoverlayui.so
#3  0xf755b005 in ?? () from /home/chris/.local/share/Steam/ubuntu12_32/libtier0_s.so
#4  0xf755b243 in CatchAndWriteMiniDumpExForVoidPtrFn () from /home/chris/.local/share/Steam/ubuntu12_32/libtier0_s.so
#5  0xf755b295 in CatchAndWriteMiniDumpForVoidPtrFn () from /home/chris/.local/share/Steam/ubuntu12_32/libtier0_s.so
#6  0xf6ff0934 in WinAppMain () from /home/chris/.local/share/Steam/ubuntu12_32/gameoverlayui.so
#7  0xf778757e in ?? ()
#8  0xf7592e2e in __libc_start_main () from /usr/lib32/libc.so.6
#9  0xf77875c5 in _start ()
```

**Comment by ChristophHaag** [comment]
I think it works now and I can close this.
