### ISSUE TITLE
Steam client crashes with "Assertion Failed: Bad thread local"

### ISSUE THREAD

**Issue by trou** [ValveSoftware/steam-for-linux#3716]
Steam on Debian Sid 64bit crashes with the following log : 
```
Running Steam on debian 8 64-bit
STEAM_RUNTIME is enabled automatically
[2015-02-14 14:44:05] Startup - updater built Jan 23 2015 13:46:31
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2015-02-14 14:44:05] Checking for update on startup
[2015-02-14 14:44:05] Checking for available updates...
[2015-02-14 14:44:06] Download skipped: /client/steam_client_ubuntu12 version 1422054110, installed version 1422054110
[2015-02-14 14:44:06] Nothing to do
[2015-02-14 14:44:06] Verifying installation...
[2015-02-14 14:44:06] Performing checksum verification of executable files
[2015-02-14 14:44:06] Verification complete
Requested Force create but SharedObjectMutex already created
Forced create but already created for SharedObjectEvent
Forced create but already created for SharedObjectEvent
Running Steam on debian 8 64-bit
STEAM_RUNTIME has been set by the user to: /home/trou/.steam/ubuntu12_32/steam-runtime
/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/tier0/threadtools.cpp (2683) : Assertion Failed: Bad thread local
```
There is a download running and steam exits at random times, sometimes after 10s, sometimes after several minutes.
It looks like a race condition somewhere.

Crash is reproducible : every time I run steam.

**Comment by trou** [comment]
Backtrace in gdb : 
```
[New Thread 0xe6482b40 (LWP 10367)]
[Thread 0xe6482b40 (LWP 10367) exited]
[Thread 0xea9ffb40 (LWP 9298) exited]

Program received signal SIGTRAP, Trace/breakpoint trap.
[Switching to Thread 0xedb52b40 (LWP 9276)]
0xedbacc1f in ?? () from /home/trou/.steam/ubuntu12_32/steamservice.so
(gdb) bt
#0  0xedbacc1f in ?? () from /home/trou/.steam/ubuntu12_32/steamservice.so
#1  0xedbb0c42 in ?? () from /home/trou/.steam/ubuntu12_32/steamservice.so
#2  0xedbb16cc in ?? () from /home/trou/.steam/ubuntu12_32/steamservice.so
#3  0xf71ccd97 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
#4  0xf7129dfe in clone () from /lib/i386-linux-gnu/libc.so.6
```
Mapping : 
```
	0xedb53000 0xedcde000   0x18b000        0x0 /home/trou/.steam/ubuntu12_32/steamservice.so
	0xedcde000 0xedce4000     0x6000   0x18a000 /home/trou/.steam/ubuntu12_32/steamservice.so
	0xedce4000 0xedce5000     0x1000   0x190000 /home/trou/.steam/ubuntu12_32/steamservice.so
	0xedce5000 0xedd00000    0x1b000        0x0 
```
Continuing after trap : 
```
(gdb) c
Continuing.
[New Thread 0xea9ffb40 (LWP 10648)]
[Thread 0xedb52b40 (LWP 9276) exited]
[Thread 0xea9ffb40 (LWP 10648) exited]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xee8b7b40 (LWP 9260)]
0xef8e9b24 in ?? () from /home/trou/.steam/ubuntu12_32/steamclient.so
(gdb) bt
#0  0xef8e9b24 in ?? () from /home/trou/.steam/ubuntu12_32/steamclient.so
#1  0xef782940 in ?? () from /home/trou/.steam/ubuntu12_32/steamclient.so
#2  0xef72f657 in ?? () from /home/trou/.steam/ubuntu12_32/steamclient.so
#3  0xef72fc50 in ?? () from /home/trou/.steam/ubuntu12_32/steamclient.so
#4  0xeef7069c in ?? () from /home/trou/.steam/ubuntu12_32/steamclient.so
#5  0xef3cf478 in ?? () from /home/trou/.steam/ubuntu12_32/steamclient.so
#6  0xeef73c85 in ?? () from /home/trou/.steam/ubuntu12_32/steamclient.so
#7  0xeef74ae0 in ?? () from /home/trou/.steam/ubuntu12_32/steamclient.so
#8  0xf5392bca in SteamThreadTools::CThread::ThreadExceptionWrapper(void*) () from /home/trou/.steam/ubuntu12_32/libtier0_s.so
#9  0xf539132c in ?? () from /home/trou/.steam/ubuntu12_32/libtier0_s.so
#10 0xf5391565 in CatchAndWriteMiniDumpExForVoidPtrFn () from /home/trou/.steam/ubuntu12_32/libtier0_s.so
#11 0xf53915b7 in CatchAndWriteMiniDumpForVoidPtrFn () from /home/trou/.steam/ubuntu12_32/libtier0_s.so
#12 0xf5394b90 in SteamThreadTools::CThread::ThreadProc(void*) () from /home/trou/.steam/ubuntu12_32/libtier0_s.so
#13 0xf71ccd97 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
#14 0xf7129dfe in clone () from /lib/i386-linux-gnu/libc.so.6
```

**Comment by trou** [comment]
It only crashes when downloading.

**Comment by trou** [comment]
Still crashing in latest version `[2015-06-07 15:48:12] Download skipped: /client/steam_client_ubuntu12 version 1433441724, installed version 1433441724`

**Comment by jepler** [comment]
Switching virtual desktops to a web browser while downloading seems to be a pretty good trigger for me.  Desktop: XFCE  Window manager: openbox

**Comment by trou** [comment]
It seems to have been fixed. Closing.
