### ISSUE TITLE
Team Fortress 2 segfaults as soon as the main menu loads

### ISSUE THREAD

**Issue by arandomhuman** [ValveSoftware/steam-for-linux#3752]
The command being run is

```
optirun ./hl2.sh -game tf -steam -nojoy -novid -autoconfig
```

The process segfaults as soon as the text in the main menu appears. Another Source game - Half Life 2 - runs normally. The behaviour when launching from Steam is identical.

I've tried to compile everything relevant I could think of, which are listed below, along with links to gists and relevant snippets. I can supply additional information if required.

**graphic card drivers:**

```
nvidia: 346.35
bumblebee: 3.2.1
```

**stdout/stderr:** [stdout output](https://gist.githubusercontent.com/arandomhuman/52179b8f1ff54f4239cd/raw/71a977db7c35e5639b48eaf8c39fcf5d43489513/TF2-stdout.log) and [stderr output](https://gist.githubusercontent.com/arandomhuman/52179b8f1ff54f4239cd/raw/342a38b68c8545ef7118eac9d24a7fc276a019af/TF2-stderr.log)

```
./hl2.sh: line 67:  7381 Segmentation fault      ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
```

**strace:** [strace output](https://gist.githubusercontent.com/arandomhuman/52179b8f1ff54f4239cd/raw/b170d84b50fd46af32b2837d60f42be90b578011/TF2-strace.log)

**dmesg:** [dmesg output](https://gist.githubusercontent.com/arandomhuman/52179b8f1ff54f4239cd/raw/0e1e37341d7c19d72e33d65eca1534ae1facc622/TF2-dmesg.log)

```
[216495.075361] traps: hl2_linux[13106] general protection ip:f75fb87a sp:fffc3338 error:0 in libc-2.19.so[f74a4000+1b6000]
```

**gdb:** [gdb output](https://gist.githubusercontent.com/arandomhuman/52179b8f1ff54f4239cd/raw/d809dc9bd068442a3388703f79dea3e9493d2a63/TF2-gdb.log)

```
 Program received signal SIGSEGV, Segmentation fault.
 0xf7eba87a in ?? () from /lib32/libc.so.6
 (gdb) bt
 #0  0xf7eba87a in ?? () from /lib32/libc.so.6
 #1  0xf70c64be in ?? () from /home/localuser/games/Steam/steamapps/common/Team Fortress 2/bin/filesystem_stdio.so
 #2  0xf70a7878 in ?? () from /home/localuser/games/Steam/steamapps/common/Team Fortress 2/bin/filesystem_stdio.so
 #3  0xf70a7cc4 in ?? () from /home/localuser/games/Steam/steamapps/common/Team Fortress 2/bin/filesystem_stdio.so
 #4  0xf7094357 in ?? () from /home/localuser/games/Steam/steamapps/common/Team Fortress 2/bin/filesystem_stdio.so
 #5  0xf70945da in ?? () from /home/localuser/games/Steam/steamapps/common/Team Fortress 2/bin/filesystem_stdio.so
 #6  0xf7094b92 in ?? () from /home/localuser/games/Steam/steamapps/common/Team Fortress 2/bin/filesystem_stdio.so
 #7  0xf70955f2 in ?? () from /home/localuser/games/Steam/steamapps/common/Team Fortress 2/bin/filesystem_stdio.so
 #8  0xf7095b98 in ?? () from /home/localuser/games/Steam/steamapps/common/Team Fortress 2/bin/filesystem_stdio.so
 #9  0xf70a127c in ?? () from /home/localuser/games/Steam/steamapps/common/Team Fortress 2/bin/filesystem_stdio.so
 #10 0xf70a4fe9 in ?? () from /home/localuser/games/Steam/steamapps/common/Team Fortress 2/bin/filesystem_stdio.so
 #11 0xf709f72f in ?? () from /home/localuser/games/Steam/steamapps/common/Team Fortress 2/bin/filesystem_stdio.so
 #12 0xeef072cf in ?? () from /home/localuser/games/Steam/steamapps/common/Team Fortress 2/bin/engine.so
 #13 0xeef08a34 in ?? () from /home/localuser/games/Steam/steamapps/common/Team Fortress 2/bin/engine.so
 #14 0xeef0814a in ?? () from /home/localuser/games/Steam/steamapps/common/Team Fortress 2/bin/engine.so
 #15 0xeef12371 in ?? () from /home/localuser/games/Steam/steamapps/common/Team Fortress 2/bin/engine.so
 #16 0xeef124e3 in ?? () from /home/localuser/games/Steam/steamapps/common/Team Fortress 2/bin/engine.so
 #17 0x23c3380b in ?? ()
 #18 0x23c341b5 in ?? ()
 #19 0xe5b65aba in ?? () from /home/localuser/games/Steam/steamapps/common/Team Fortress 2/bin/vaudio_miles.so
 #20 0xe5b65e93 in ?? () from /home/localuser/games/Steam/steamapps/common/Team Fortress 2/bin/vaudio_miles.so
 #21 0xe5b65fbc in ?? () from /home/localuser/games/Steam/steamapps/common/Team Fortress 2/bin/vaudio_miles.so
 #22 0xeef122f7 in ?? () from /home/localuser/games/Steam/steamapps/common/Team Fortress 2/bin/engine.so
 #23 0xeef1256c in ?? () from /home/localuser/games/Steam/steamapps/common/Team Fortress 2/bin/engine.so
 #24 0xeef04b10 in ?? () from /home/localuser/games/Steam/steamapps/common/Team Fortress 2/bin/engine.so
 #25 0xeeed641a in ?? () from /home/localuser/games/Steam/steamapps/common/Team Fortress 2/bin/engine.so
 #26 0xeeee33d5 in ?? () from /home/localuser/games/Steam/steamapps/common/Team Fortress 2/bin/engine.so
 #27 0xeeee4698 in ?? () from /home/localuser/games/Steam/steamapps/common/Team Fortress 2/bin/engine.so
 #28 0xeeee59be in ?? () from /home/localuser/games/Steam/steamapps/common/Team Fortress 2/bin/engine.so
 #29 0xeeee5a6e in ?? () from /home/localuser/games/Steam/steamapps/common/Team Fortress 2/bin/engine.so
 #30 0xeef9fdba in ?? () from /home/localuser/games/Steam/steamapps/common/Team Fortress 2/bin/engine.so
 #31 0xeef9ff12 in ?? () from /home/localuser/games/Steam/steamapps/common/Team Fortress 2/bin/engine.so
 #32 0xeefa0145 in ?? () from /home/localuser/games/Steam/steamapps/common/Team Fortress 2/bin/engine.so
 #33 0xef03c2f4 in ?? () from /home/localuser/games/Steam/steamapps/common/Team Fortress 2/bin/engine.so
 #34 0xef03dda8 in ?? () from /home/localuser/games/Steam/steamapps/common/Team Fortress 2/bin/engine.so
 #35 0xef0579b1 in ?? () from /home/localuser/games/Steam/steamapps/common/Team Fortress 2/bin/engine.so
 #36 0xef057c1e in ?? () from /home/localuser/games/Steam/steamapps/common/Team Fortress 2/bin/engine.so
 #37 0xef057d29 in ?? () from /home/localuser/games/Steam/steamapps/common/Team Fortress 2/bin/engine.so
 #38 0xef140b3a in ?? () from /home/localuser/games/Steam/steamapps/common/Team Fortress 2/bin/engine.so
 #39 0xef13d38f in ?? () from /home/localuser/games/Steam/steamapps/common/Team Fortress 2/bin/engine.so
 #40 0xef13d49d in ?? () from /home/localuser/games/Steam/steamapps/common/Team Fortress 2/bin/engine.so
 #41 0xef197a80 in ?? () from /home/localuser/games/Steam/steamapps/common/Team Fortress 2/bin/engine.so
 #42 0xef13eb2f in ?? () from /home/localuser/games/Steam/steamapps/common/Team Fortress 2/bin/engine.so
 #43 0xf7f74a00 in ?? () from bin/launcher.so
 #44 0xf7f74a00 in ?? () from bin/launcher.so
 #45 0xf7f5865d in LauncherMain () from bin/launcher.so
 #46 0x0804877b in main ()
```

**System Information:** [copy with failure reports](https://gist.githubusercontent.com/arandomhuman/52179b8f1ff54f4239cd/raw/3a6fc032221a3f758d72795b23c34ef22fe2e0af/TF2-sysinfo.log)

```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3100 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "Sabayon Linux amd64 15.03" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.19.0-sabayon
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11604000
    X Window Manager:  Marco
    Steam Runtime Version:  steam-runtime-release_2015-01-06

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Ivybridge Mobile 

    Driver Version:  3.0 Mesa 10.5.0-rc1
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID Not Detected
    DeviceID Not Detected
    Number of Monitors:  1
    Number of Video Cards Not Detected
    Primary Display Resolution:  1366 x 768
    Desktop Resolution: 1366 x 768
    Primary Display Size: 13.54" x 7.64"  (15.51" diag)
                                            34.4cm x 19.4cm  (39.4cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: Intel PantherPoint HDMI

Memory:
    RAM:  7846 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  403045 Mb
    Largest Free Hard Disk Block:  50190 Mb

Installed software:

```

Thanks for your help.

**Comment by ennui93** [comment]
I'm seeing a very similar segfault on TF2 in the same place -- just after the main menu is drawn. I am launching directly from a freshly downloaded/installed copy of Steam and TF2.

Relevant information can be found in the gist at https://gist.github.com/ennui93/740d94a0e1074eb811e9 . The most interesting strace will be tf2.8921. Stack trace included below so others may compare against their segfault to see if they have the same failure pattern.

```
Program received signal SIGSEGV, Segmentation fault.
0xeba9bf7a in ?? () from /lib/libc.so.6
(gdb) bt
#0  0xeba9bf7a in ?? () from /lib/libc.so.6
#1  0xe69dd38e in ?? () from /usr/local/SteamLibrary/steamapps/common/Team Fortress 2/bin/filesystem_stdio.so
#2  0xe69be7d8 in ?? () from /usr/local/SteamLibrary/steamapps/common/Team Fortress 2/bin/filesystem_stdio.so
#3  0xe69bec24 in ?? () from /usr/local/SteamLibrary/steamapps/common/Team Fortress 2/bin/filesystem_stdio.so
#4  0xe69ab2b7 in ?? () from /usr/local/SteamLibrary/steamapps/common/Team Fortress 2/bin/filesystem_stdio.so
#5  0xe69ab53a in ?? () from /usr/local/SteamLibrary/steamapps/common/Team Fortress 2/bin/filesystem_stdio.so
#6  0xe69abaf2 in ?? () from /usr/local/SteamLibrary/steamapps/common/Team Fortress 2/bin/filesystem_stdio.so
#7  0xe69ac552 in ?? () from /usr/local/SteamLibrary/steamapps/common/Team Fortress 2/bin/filesystem_stdio.so
#8  0xe69acaf8 in ?? () from /usr/local/SteamLibrary/steamapps/common/Team Fortress 2/bin/filesystem_stdio.so
#9  0xe69b81dc in ?? () from /usr/local/SteamLibrary/steamapps/common/Team Fortress 2/bin/filesystem_stdio.so
#10 0xe69bbf49 in ?? () from /usr/local/SteamLibrary/steamapps/common/Team Fortress 2/bin/filesystem_stdio.so
#11 0xe69b668f in ?? () from /usr/local/SteamLibrary/steamapps/common/Team Fortress 2/bin/filesystem_stdio.so
#12 0xe58ae4ef in ?? () from /usr/local/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#13 0xe58afc54 in ?? () from /usr/local/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#14 0xe58af36a in ?? () from /usr/local/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#15 0xe58b9591 in ?? () from /usr/local/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#16 0xe58b9703 in ?? () from /usr/local/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#17 0x123d580b in ?? ()
#18 0x123d61b5 in ?? ()
#19 0xe68f2aba in ?? () from /usr/local/SteamLibrary/steamapps/common/Team Fortress 2/bin/vaudio_miles.so
#20 0xe68f2e93 in ?? () from /usr/local/SteamLibrary/steamapps/common/Team Fortress 2/bin/vaudio_miles.so
#21 0xe68f2fbc in ?? () from /usr/local/SteamLibrary/steamapps/common/Team Fortress 2/bin/vaudio_miles.so
#22 0xe58b9517 in ?? () from /usr/local/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#23 0xe58b978c in ?? () from /usr/local/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#24 0xe58a8670 in ?? () from /usr/local/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#25 0xe5878a9a in ?? () from /usr/local/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#26 0xe5885a55 in ?? () from /usr/local/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#27 0xe5886d18 in ?? () from /usr/local/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#28 0xe588803e in ?? () from /usr/local/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#29 0xe58880ee in ?? () from /usr/local/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#30 0xe594700a in ?? () from /usr/local/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#31 0xe5947162 in ?? () from /usr/local/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#32 0xe5947395 in ?? () from /usr/local/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#33 0xe59e3544 in ?? () from /usr/local/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#34 0xe59e4ff8 in ?? () from /usr/local/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#35 0xe59fec01 in ?? () from /usr/local/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#36 0xe59fee6e in ?? () from /usr/local/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#37 0xe59fef79 in ?? () from /usr/local/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#38 0xe5ae7d8a in ?? () from /usr/local/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#39 0xe5ae45df in ?? () from /usr/local/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#40 0xe5ae46ed in ?? () from /usr/local/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#41 0xe5b3ecc0 in ?? () from /usr/local/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#42 0xe5ae5d7f in ?? () from /usr/local/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#43 0xe746a8d0 in ?? () from bin/launcher.so
#44 0xe746a8d0 in ?? () from bin/launcher.so
#45 0xe744e5bd in LauncherMain () from bin/launcher.so
#46 0x0804877b in main ()
```

**Comment by kisak-valve** [comment]
Hello @arandomhuman, @ennui93, are either of you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
If either of you still seeing this issue, please open a new issue report in the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games) issue tracker.
