### ISSUE TITLE
Sid Meyer's Civilization V: Complete Edition - crashes on launch (Ubuntu 14.04)

### ISSUE THREAD

**Issue by SteelShad0w** [ValveSoftware/steam-for-linux#3754]
After successfully installing the Steam client and Sid Meier's Civilization V: Complete Edition onto my device, I attempted to launch the game both from my desktop and from the Steam client. The small "Preparing to launch..." dialogue box appears for about half a second before disappearing and yielding no further response from the game or client (as though I had never attempted to launch it). Other games (such as RoboCraft and Gary's Mod) run fine upon launch. My hardware specs are as follows:

Running Ubuntu 14.04 64-bit
Memory: 8 gb ram
Processor: Intel Celeron(R) 2955U @ 1.40GHz × 2
Graphics: Intel Haswell Mobile

I originally thought it was a problem with my graphics drivers but I now have OpenGL 3.3 installed and I still get the same problem with it failing to launch. I am unsure how to get any terminal response to help diagnose the problem (as I simply launch the game from a window or the client), but if instructed on how to do so I can try to provide an output. 
Thanks for your time.

**Comment by gdrewb-valve** [comment]
You should report this to the developer also.

**Comment by myromance123** [comment]
Running the game from a Terminal in Ubuntu should be as easy as typing in the following and hitting Enter:
```bash
steam steam://rungameid/8930
```
Where the numbers 8930 are the ID number of the game you want to run. You can do this for any game in Steam, as long as you supply the correct ID number. Any error outputs will let you and us determine if it is actually a game issue, driver issue or steam related issue.

**Comment by TierraDelFuego** [comment]
@myromance123 I tried your suggestion and got not useful output.  However I did notice that, while at the command line, ps tells me that the game is running. But if I switch back to to the gui there's no game running. The game exited when I switch to the gui. And the "Time played" counter increments also. So if I stay at the command line for 5 minutes before switching back to the gui 5 minutes will be added to the total "Time played" stat.

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue on an up to date system?

**Comment by boombatower** [comment]
Are you running the Steam Beta? If so likely related to #5546.

**Comment by boombatower** [comment]
Hehe, didn't see the original post date is old so assume was different, but perhaps the same. Anyway figured people might find this issue.

**Comment by hzhangxyz** [comment]
Same here, Civilization V crashed on launch, log is here:

```
GameAction [AppID 8930, ActionID 4] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 8930, ActionID 4] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 8930, ActionID 4] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 8930, ActionID 4] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 8930, ActionID 4] : LaunchApp continues with user response "CreatingProcess"
Opted-in Controller Mask: 30
Game update: AppID 8930 "", ProcID 18294, IP 0.0.0.0:0
>>> Adding process 18294 for game ID 8930
GameAction [AppID 8930, ActionID 4] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/hzhangxyz/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/hzhangxyz/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
GameAction [AppID 8930, ActionID 4] : LaunchApp changed task to Completed with ""
>>> Adding process 18295 for game ID 8930
GUID Assets\dlc\dlc_01\mongol.civ5pkg 7a036b7fb9a80e8dea7b73fb58c5a288
GUID Assets\dlc\shared\upgrade1.civ5pkg e818fa28902977b42ee5e3426f5112e6
Game update: AppID 8930 "", ProcID 18295, IP 0.0.0.0:0
Setting breakpad minidump AppID = 8930
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198403947352 [API loaded no]
Installing breakpad exception handler for appid(gameoverlayui)/version(20180608222225)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Game removed: AppID 8930 "", ProcID 18295
No cached sticky mapping in ActivateActionSet.
```

**Comment by hzhangxyz** [comment]
when i run `gdb %command%`, I got the following:
```
(gdb) run
Starting program: /home/hzhangxyz/.local/share/Steam/steamapps/common/Sid Meier's Civilization V/Civ5XP
ERROR: ld.so: object '/home/hzhangxyz/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/hzhangxyz/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
>>> Adding process 347 for game ID 8930
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
warning: the debug information found in "./libopenal.so.1.13.0" does not match "./libopenal.so.1" (CRC mismatch).

warning: the debug information found in "./libuuid.so.1.3.0" does not match "./libuuid.so.1" (CRC mismatch).

[New Thread 0xf5f26b40 (LWP 349)]
[New Thread 0xf49bfb40 (LWP 350)]
[New Thread 0xf3dffb40 (LWP 351)]
GUID Assets\dlc\dlc_01\mongol.civ5pkg 7a036b7fb9a80e8dea7b73fb58c5a288
GUID Assets\dlc\shared\upgrade1.civ5pkg e818fa28902977b42ee5e3426f5112e6
Game update: AppID 8930 "", ProcID 347, IP 0.0.0.0:0
Setting breakpad minidump AppID = 8930
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198403947352 [API loaded no]
Installing breakpad exception handler for appid(gameoverlayui)/version(20180608222225)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
[New Thread 0xee8ffb40 (LWP 354)]
[New Thread 0xee6feb40 (LWP 355)]
[New Thread 0xee4fdb40 (LWP 356)]
[New Thread 0xee0ffb40 (LWP 357)]
[New Thread 0xedcffb40 (LWP 358)]
[New Thread 0xedafeb40 (LWP 359)]
[New Thread 0xf27ffb40 (LWP 360)]
[New Thread 0xebd41b40 (LWP 361)]
[Thread 0xebd41b40 (LWP 361) exited]
[New Thread 0xebd41b40 (LWP 362)]

Thread 4 "Civ5XP" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xf3dffb40 (LWP 351)]
0xf25624e1 in pa_smoother_new () from /usr/lib32/pulseaudio/libpulsecommon-12.0.so
(gdb) Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
bt
#0  0xf25624e1 in pa_smoother_new () from /usr/lib32/pulseaudio/libpulsecommon-12.0.so
#1  0xf25cc9d4 in ?? () from /usr/lib32/libpulse.so.0
#2  0xf783d09b in ?? () from ./libopenal.so.1
#3  0xf783d32c in ?? () from ./libopenal.so.1
#4  0xf78149a3 in alcCreateContext () from ./libopenal.so.1
#5  0x09126f4a in YUV12 ()
#6  0x091264a2 in YUV12 ()
#7  0x09113bee in check_for_pending_io ()
#8  0x09114188 in BinkOpen ()
#9  0x085f7553 in ASL::PlayBinkMovieGL(char const*, float, unsigned int, unsigned int, bool*) ()
#10 0x0884c26c in PlayMovieState::Begin() ()
#11 0x086e0fc3 in Civ5App::PlayOpeningMovie() ()
#12 0x086e1c46 in Civ5App::Init(char const*) ()
#13 0x0865b3ed in WinMain ()
#14 0x085f5487 in ?? ()
#15 0x085d8e3e in ThreadHANDLE::ThreadProc(void*) ()
#16 0xf7b7138f in start_thread () from /usr/lib32/libpthread.so.0
#17 0xf79b68b6 in clone () from /usr/lib32/libc.so.6
(gdb) info threads
  Id   Target Id         Frame
  1    Thread 0xf73c29c0 (LWP 347) "Civ5XP" 0xf7fd4de9 in __kernel_vsyscall ()
  2    Thread 0xf5f26b40 (LWP 349) "SDLTimer" 0xf7fd4de9 in __kernel_vsyscall ()
  3    Thread 0xf49bfb40 (LWP 350) "disk_cache:0" 0xf7fd4de9 in __kernel_vsyscall ()
* 4    Thread 0xf3dffb40 (LWP 351) "Civ5XP" 0xf25624e1 in pa_smoother_new () from /usr/lib32/pulseaudio/libpulsecommon-12.0.so
  5    Thread 0xee8ffb40 (LWP 354) "Civ5XP" 0xf7fd4de9 in __kernel_vsyscall ()
  6    Thread 0xee6feb40 (LWP 355) "Civ5XP" 0xf7fd4de9 in __kernel_vsyscall ()
  7    Thread 0xee4fdb40 (LWP 356) "Civ5XP" 0xf7fd4de9 in __kernel_vsyscall ()
  8    Thread 0xee0ffb40 (LWP 357) "Civ5XP" 0xf7fd4de9 in __kernel_vsyscall ()
  9    Thread 0xedcffb40 (LWP 358) "Civ5XP" 0xf7fd4de9 in __kernel_vsyscall ()
  10   Thread 0xedafeb40 (LWP 359) "Civ5XP" 0xf7fd4de9 in __kernel_vsyscall ()
  11   Thread 0xf27ffb40 (LWP 360) "Civ5XP" 0xf7fd4de9 in __kernel_vsyscall ()
  13   Thread 0xebd41b40 (LWP 362) "threaded-ml" 0xf7fd4de9 in __kernel_vsyscall ()
(gdb)
```
