### ISSUE TITLE
Steam segfaults on launch

### ISSUE THREAD

**Issue by ace13** [ValveSoftware/steam-for-linux#3988]
Today after restarting my computer Steam has started segfaulting on launch, I tried completely removing all steam files and letting it reinstall without any difference.

```
$ steam
/home/ace/.local/share/Steam/steam.sh: line 159: DISTRIB_RELEASE: unbound variable
/home/ace/.local/share/Steam/steam.sh: line 159: DISTRIB_RELEASE: unbound variable
Running Steam on sabayon  64-bit
/home/ace/.local/share/Steam/steam.sh: line 159: DISTRIB_RELEASE: unbound variable
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1440016726)
Installing breakpad exception handler for appid(steam)/version(1440016726)
Installing breakpad exception handler for appid(steam)/version(1440016726)
Installing breakpad exception handler for appid(steam)/version(1440016726)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
[0828/000232:ERROR:browser_main_loop.cc(173)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
Installing breakpad exception handler for appid(steamwebhelper)/version(20150819112727)
Installing breakpad exception handler for appid(steamwebhelper)/version(1439983647)
Installing breakpad exception handler for appid(steamwebhelper)/version(20150819112727)
Installing breakpad exception handler for appid(steamwebhelper)/version(1440016726)
Installing breakpad exception handler for appid(steamwebhelper)/version(1440016726)
Installing breakpad exception handler for appid(steam)/version(1440016726)
Installing breakpad exception handler for appid(steam)/version(1440016726)
Installing breakpad exception handler for appid(steam)/version(1440016726)
Installing breakpad exception handler for appid(steam)/version(1440016726)
Installing breakpad exception handler for appid(steam)/version(1440016726)
Installing breakpad exception handler for appid(steam)/version(1440016726)
FillInMachineIDInfo took a total of 0 milliseconds
Installing breakpad exception handler for appid(steam)/version(1440016726)
Dongle firmware /home/ace/.local/share/Steam/ubuntu12_32/../controller_base/d0ggle.bin loaded, version 1435869091.
Installing breakpad exception handler for appid(steam)/version(1440016726)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
[0828/000232:ERROR:renderer_main.cc(200)] Running without renderer sandbox
[0828/000232:ERROR:renderer_main.cc(200)] Running without renderer sandbox
assert_20150828000230_1.dmp[10268]: Uploading dump (out-of-process)
/tmp/dumps/assert_20150828000230_1.dmp
/home/ace/.local/share/Steam/steam.sh: line 756: 10217 Segmentation fault      $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
[0828/000233:WARNING:channel.cc(549)] Failed to send message to ack remove remote endpoint (local ID 1, remote ID 1)
[0828/000233:WARNING:channel.cc(549)] Failed to send message to ack remove remote endpoint (local ID 2147483648, remote ID 2)
[0828/000233:WARNING:channel.cc(549)] Failed to send message to ack remove remote endpoint (local ID 1, remote ID 1)
[0828/000233:WARNING:channel.cc(549)] Failed to send message to ack remove remote endpoint (local ID 2147483648, remote ID 2)
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
assert_20150828000230_1.dmp[10268]: Finished uploading minidump (out-of-process): success = yes
assert_20150828000230_1.dmp[10268]: response: CrashID=bp-1947bcb1-dd2f-4c4d-9cc9-03bcb2150827
assert_20150828000230_1.dmp[10268]: file ''/tmp/dumps/assert_20150828000230_1.dmp'', upload yes: ''CrashID=bp-1947bcb1-dd2f-4c4d-9cc9-03bcb2150827''
```

I also tried running it with a debugger but that didn't give much useful information either

```
Program received signal SIGSEGV, Segmentation fault.
0xf24717e8 in ?? () from /home/ace/.local/share/Steam/ubuntu12_32/vgui2_s.so
(gdb) bt
#0  0xf24717e8 in ?? () from /home/ace/.local/share/Steam/ubuntu12_32/vgui2_s.so
#1  0xf2472a83 in ?? () from /home/ace/.local/share/Steam/ubuntu12_32/vgui2_s.so
#2  0xf4cd7178 in ?? () from /home/ace/.local/share/Steam/ubuntu12_32/steamui.so
#3  0xf4c823ba in ?? () from /home/ace/.local/share/Steam/ubuntu12_32/steamui.so
#4  0xf4d2adca in ?? () from /home/ace/.local/share/Steam/ubuntu12_32/steamui.so
#5  0xf4cd7b41 in ?? () from /home/ace/.local/share/Steam/ubuntu12_32/steamui.so
#6  0xf4cdd56d in ?? () from /home/ace/.local/share/Steam/ubuntu12_32/steamui.so
#7  0xf24715b6 in ?? () from /home/ace/.local/share/Steam/ubuntu12_32/vgui2_s.so
#8  0xf247269f in ?? () from /home/ace/.local/share/Steam/ubuntu12_32/vgui2_s.so
#9  0xf244d16a in ?? () from /home/ace/.local/share/Steam/ubuntu12_32/vgui2_s.so
#10 0xf2456bec in ?? () from /home/ace/.local/share/Steam/ubuntu12_32/vgui2_s.so
#11 0xf245a38a in ?? () from /home/ace/.local/share/Steam/ubuntu12_32/vgui2_s.so
#12 0xf245c36c in ?? () from /home/ace/.local/share/Steam/ubuntu12_32/vgui2_s.so
#13 0xf246b72d in ?? () from /home/ace/.local/share/Steam/ubuntu12_32/vgui2_s.so
#14 0xf47f69d7 in ?? () from /home/ace/.local/share/Steam/ubuntu12_32/steamui.so
#15 0xf47f769e in ?? () from /home/ace/.local/share/Steam/ubuntu12_32/steamui.so
#16 0x56597110 in RunSteam(int, char**, bool) ()
#17 0x5657e09e in ?? ()
#18 0xf7b63f66 in __libc_start_main () from /lib32/libc.so.6
#19 0x56580e25 in _start ()
```

Running latest Sabayonlinux 64-bit, with Intel HD Graphics 4400 if that is of any help.

**Comment by Tele42** [comment]
Does the arch steam runtime workaround help? (https://wiki.archlinux.org/index.php/Steam#Steam_runtime_issues)

**Comment by ace13** [comment]
The arch workaround did nothing at all, exact same issue with the exact same backtrace.

**Comment by ace13** [comment]
I'm going to close this as stale, unable to reproduce it as the harddrive died any my new install has not had a single Steam segfault in three months
