### ISSUE TITLE
vgui2_s.so crashing (SIGABRT) on nVidia driver version 358.16 libGL

### ISSUE THREAD

**Issue by LeonardKoenig** [ValveSoftware/steam-for-linux#4242]
Rather 'randomly' steam crashes with SIGABRT when interacting with GUI elements (but also when it's running in background but the GUI is updated, eg. for notifications).

System Info:

```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3800 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    Linux (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.3.3-2-ck
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11800000
    X Window Manager:  i3
    Steam Runtime Version:  steam-runtime-release_2015-06-12
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 970/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 358.16
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x13c2
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 3840 x 1080
    Primary Display Size: 20,91" x 11,77"  (23,98" diag)
                                            53,1cm x 29,9cm  (60,9cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 4096 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: 
    
Memory:
    RAM:  15971 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  80505 Mb
    Largest Free Hard Disk Block:  25831 Mb
    
Installed software:
    
Recent Failure Reports:
    Fri Jan  8 16:00:25 2016 GMT: file ''/tmp/dumps/assert_20160108165940_1.dmp'', upload yes: ''CrashID=bp-58808bd0-54b2-4ca2-bae0-4f43f2160108''
    
```

One particular case with all logs I could gather:
* PID of 'main' Steam process for later reference: 6608
* minidump: assert_20160108170043_1.dmp (it's sadly empty though, there wasn't even a `writing minidump` in the log. Also I forgot to generate a core file)

```
Program received signal SIGABRT, Aborted.
0xf77d7bd0 in __kernel_vsyscall ()
```

Last call by a steam program (complete backtrace here: https://gist.github.com/LeonardKoenig/c64f7dca6dc3047e73b7#file-bt):
```
#18 0xf6b57749 in glXMakeCurrent () from /usr/lib32/libGL.so.1
#19 0xef9edd9c in ?? () from /home/leonard/.local/share/Steam/ubuntu12_32/vgui2_s.so
```

The address where everything went wrong:
```
#19 0xef9edd9c in ?? () from /home/leonard/.local/share/Steam/ubuntu12_32/vgui2_s.so

0xef9a8580 - 0xefa5087c is .text in /home/leonard/.local/share/Steam/ubuntu12_32/vgui2_s.so

Symbols from "/home/leonard/.local/share/Steam/ubuntu12_32/vgui2_s.so".
        0x00016580 - 0x000be87c is .text
```

So we have an offset of `0x4581C` which gives us a base address of `0x5BD9C` in the `vgui2_s.so`, which corresponds to this snippet:

```asm
   0x5bd94:     mov    %eax,(%esp)
   0x5bd97:     call   0x152e0 <glXMakeCurrent@plt>
   0x5bd9c:     lea    0xb0(%esp),%eax
```

All logs etc:
https://gist.github.com/LeonardKoenig/c64f7dca6dc3047e73b7

Some other dumps / corresponding core files (created with breakpad minidump-2-core) I've found which seem to be related:
https://drive.google.com/file/d/0B2gXBp6AAG7fbkhEV3oxRkRRSTA/view?usp=sharing

**Comment by gdrewb-valve** [comment]
I believe the problem is in the 358 drivers.

**Comment by LeonardKoenig** [comment]
Well, on the one hand iirc the bug didn't happen before, but on the other hand I don't have any issues with those drivers. I've tried debugging but couldn't find any hint on whether it's the one or the other way ;/

**Comment by Plagman** [comment]
The 358.x drivers are known to have issues affecting the Steam Client and other apps; it's unsupported with the Steam client and the 361 beta driver should be used instead.
