### ISSUE TITLE
Ubuntu 14.04, NVIDIA-361, segmentation fault

### ISSUE THREAD

**Issue by tliron** [ValveSoftware/steam-for-linux#4271]
I'm getting the following segmentation fault:

```
/home/emblemparade/.local/share/Steam/steam.sh: line 756:  7496 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
assert_20160119185101_1.dmp[7534]: Finished uploading minidump (out-of-process): success = yes
assert_20160119185101_1.dmp[7534]: response: CrashID=bp-97504c57-f6fd-4e9a-830b-345c02160119
assert_20160119185101_1.dmp[7534]: file ''/tmp/dumps/assert_20160119185101_1.dmp'', upload yes: ''CrashID=bp-97504c57-f6fd-4e9a-830b-345c02160119''
```

Inspecting with a debugger:

```
#0  0xf7bebb79 in strstr () from /lib/i386-linux-gnu/libc.so.6
#1  0xf033aa93 in ?? () from /home/emblemparade/.local/share/Steam/ubuntu12_32/vgui2_s.so
#2  0xf033b45a in ?? () from /home/emblemparade/.local/share/Steam/ubuntu12_32/vgui2_s.so
#3  0xf02f801d in ?? () from /home/emblemparade/.local/share/Steam/ubuntu12_32/vgui2_s.so
#4  0xf02f833d in ?? () from /home/emblemparade/.local/share/Steam/ubuntu12_32/vgui2_s.so
#5  0xf031c3b9 in ?? () from /home/emblemparade/.local/share/Steam/ubuntu12_32/vgui2_s.so
#6  0xf34ac89e in ?? () from /home/emblemparade/.local/share/Steam/ubuntu12_32/steamui.so
#7  0xf34df547 in ?? () from /home/emblemparade/.local/share/Steam/ubuntu12_32/steamui.so
#8  0xf34e88d7 in ?? () from /home/emblemparade/.local/share/Steam/ubuntu12_32/steamui.so
#9  0xf34ad3be in ?? () from /home/emblemparade/.local/share/Steam/ubuntu12_32/steamui.so
#10 0xf34aedfa in ?? () from /home/emblemparade/.local/share/Steam/ubuntu12_32/steamui.so
#11 0xf353bcdf in ?? () from /home/emblemparade/.local/share/Steam/ubuntu12_32/steamui.so
#12 0xf353d48a in ?? () from /home/emblemparade/.local/share/Steam/ubuntu12_32/steamui.so
#13 0xf348404e in ?? () from /home/emblemparade/.local/share/Steam/ubuntu12_32/steamui.so
#14 0xf312e8bc in ?? () from /home/emblemparade/.local/share/Steam/ubuntu12_32/steamui.so
#15 0xf3130f85 in ?? () from /home/emblemparade/.local/share/Steam/ubuntu12_32/steamui.so
#16 0xf305b7ef in ?? () from /home/emblemparade/.local/share/Steam/ubuntu12_32/steamui.so
#17 0xf30963cb in ?? () from /home/emblemparade/.local/share/Steam/ubuntu12_32/steamui.so
#18 0xf3004335 in ?? () from /home/emblemparade/.local/share/Steam/ubuntu12_32/steamui.so
#19 0x56596610 in RunSteam(int, char**, bool) ()
#20 0x5657e59e in ?? ()
#21 0xf7b89a83 in __libc_start_main () from /lib/i386-linux-gnu/libc.so.6
#22 0x56580f05 in _start ()
```

I tried reverting to older version of the NVIDIA driver with the same results. :( Everything worked fine a few days ago, I don't know what is wrong, but I can no longer use Steam.

Using the open source NVIDIA driver is not an option for me: my machine will not run at all with it. (I have a GTX 980.)

I hear there is a beta Steam client that might fix it, but how can I opt in to the beta when I can't run the client?!

**Comment by Plagman** [comment]
Sounds like this crash might be independent from the NVIDIA driver then; to opt into the Beta from the command line, try this:
```
cd ~/.local/share/Steam/package
echo publicbeta > beta
```

**Comment by tliron** [comment]
Thanks! Unfortunately, the beta still crashes in the same libraries. :/ Any ideas how I can help youi debug this?

**Comment by Plagman** [comment]
Upload one of the .dmp files saved on disk when this segmentation fault happens, so we can examine the crash condition.

**Comment by tliron** [comment]
Here's a fresh one:

https://www.dropbox.com/s/vxkp02dqjp59ttq/assert_20160120200041_1.dmp?dl=0

**Comment by tliron** [comment]
Good news? Today's beta update fixed things for me: Steam runs. But I really hope you guys know what you did that fixed it. Is that .dmp helpful? I'm happy to do anything you ask to help you understand the issue.

**Comment by kisak-valve** [comment]
Closing per the last comment.
