### ISSUE TITLE
Bastion crashes if started from Steam client

### ISSUE THREAD

**Issue by lumag** [ValveSoftware/steam-for-linux#4322]
I'm getting the following error if I start Bastion from the Steam client. Starting it manually works w/o any issues.

Host: Debian testing x86_64. PulseAudio is installed and running.

```
Game update: AppID 107100 "Bastion", ProcID 4072, IP 0.0.0.0:0
ERROR: ld.so: object '/home/lumag/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/bin/sh: /home/lumag/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /bin/sh)
ERROR: ld.so: object '/home/lumag/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/bin/bash: /home/lumag/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /bin/bash)
ERROR: ld.so: object '/home/lumag/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
Setting breakpad minidump AppID = 107100
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198034683638 [API loaded no]
Number of joysticks: 0
Installing breakpad exception handler for appid(gameoverlayui)/version(20160211153213)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
initializing c# fmod
ERROR: ld.so: object '/home/lumag/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
sh: /home/lumag/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by sh)
Stacktrace:

  at (wrapper managed-to-native) FMOD.System.FMOD_System_Init (intptr,int,FMOD.INITFLAGS,intptr) <0xffffffff>
  at FMOD.System.init (int,FMOD.INITFLAGS,intptr) <0x0001b>
  at FMOD.Framework.init () <0x000ab>
  at Microsoft.Xna.Framework.Audio.AudioEngine..ctor (string) <0x00277>
  at GSGE.AudioManager..ctor (Microsoft.Xna.Framework.Game,string,string,string,string) <0x000b3>
  at GSGE.AudioManager.Initialize (Microsoft.Xna.Framework.Game,string,string,string,string) <0x00083>
  at GSGE.Code.GUI.LoadScreen.splashSequence (Microsoft.Xna.Framework.GameTime) <0x000c3>
  at GSGE.Code.GUI.LoadScreen.Update (Microsoft.Xna.Framework.GameTime,bool,bool) <0x002c3>
  at GSGE.ScreenManager.updateScreen (Microsoft.Xna.Framework.GameTime,bool,bool,GSGE.GameScreen) <0x0001b>
  at GSGE.ScreenManager.updateInternal (Microsoft.Xna.Framework.GameTime) <0x001c7>
  at GSGE.ScreenManager.Update (Microsoft.Xna.Framework.GameTime) <0x00017>
  at Microsoft.Xna.Framework.Game.<UpdateAction>m__D (Microsoft.Xna.Framework.IUpdateable,Microsoft.Xna.Framework.GameTime) <0x0001b>
  at Microsoft.Xna.Framework.Game/SortingFilteringCollection`1.ForEachFilteredItem<TUserData> (System.Action`2<T, TUserData>,TUserData) <0x001ba>
  at Microsoft.Xna.Framework.Game.Update (Microsoft.Xna.Framework.GameTime) <0x00027>
  at GSGE.App.Update (Microsoft.Xna.Framework.GameTime) <0x000a7>
  at Microsoft.Xna.Framework.Game.DoUpdate (Microsoft.Xna.Framework.GameTime) <0x00038>
  at Microsoft.Xna.Framework.Game.Tick () <0x00313>
  at Microsoft.Xna.Framework.GameWindow.OnUpdateFrame (object,OpenTK.FrameEventArgs) <0x0002f>
  at (wrapper delegate-invoke) <Module>.invoke_void__this___object_FrameEventArgs (object,OpenTK.FrameEventArgs) <0xffffffff>
  at OpenTK.GameWindow.OnUpdateFrame (OpenTK.FrameEventArgs) <0x00019>
  at OpenTK.GameWindow.OnUpdateFrameInternal (OpenTK.FrameEventArgs) <0x00034>
  at OpenTK.GameWindow.RaiseUpdateFrame (System.Diagnostics.Stopwatch,double&,OpenTK.FrameEventArgs) <0x00107>
  at OpenTK.GameWindow.DispatchUpdateAndRenderFrame (object,System.EventArgs) <0x00027>
  at OpenTK.GameWindow.Run (double,double) <0x00273>
  at OpenTK.GameWindow.Run () <0x00023>
  at Microsoft.Xna.Framework.GameWindow.Run (double) <0x00027>
  at Microsoft.Xna.Framework.LinuxGamePlatform.RunLoop () <0x00037>
  at Microsoft.Xna.Framework.Game.Run (Microsoft.Xna.Framework.GameRunBehavior) <0x00113>
  at Microsoft.Xna.Framework.Game.Run () <0x00027>
  at GSGE.App.Run<T> () <0x000d3>
  at GSGE.App.Main (string[]) <0x0026b>
  at (wrapper runtime-invoke) <Module>.runtime_invoke_void_object (object,intptr,intptr,intptr) <0xffffffff>

Native stacktrace:

	/home/lumag/.local/share/Steam/steamapps/common/Bastion/Linux/lib/libmono-2.0.so.1(+0xa5848) [0xf750b848]
	/home/lumag/.local/share/Steam/steamapps/common/Bastion/Linux/lib/libmono-2.0.so.1(+0xec8b4) [0xf75528b4]
	/home/lumag/.local/share/Steam/steamapps/common/Bastion/Linux/lib/libmono-2.0.so.1(+0x1c740) [0xf7482740]
	linux-gate.so.1(__kernel_rt_sigreturn+0) [0xf778ebc0]

Debug info from gdb:

ERROR: ld.so: object '/home/lumag/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/usr/bin/gdb: /home/lumag/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libncurses.so.5: no version information available (required by /usr/bin/gdb)
/usr/bin/gdb: /home/lumag/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libncurses.so.5: no version information available (required by /usr/bin/gdb)
/usr/bin/gdb: /home/lumag/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /usr/bin/gdb)
/usr/bin/gdb: /home/lumag/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /lib/x86_64-linux-gnu/libreadline.so.6)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
[New LWP 4081]
[New LWP 4080]
[New LWP 4079]
[New LWP 4078]
[New LWP 4077]
[New LWP 4076]
[New LWP 4075]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0xf778ebe0 in __kernel_vsyscall ()
  Id   Target Id         Frame 
  8    Thread 0xf58beb40 (LWP 4075) "Bastion.bin.x86" 0xf778ebe0 in __kernel_vsyscall ()
  7    Thread 0xf50bdb40 (LWP 4076) "Bastion.bin.x86" 0xf778ebe0 in __kernel_vsyscall ()
  6    Thread 0xf48bcb40 (LWP 4077) "Bastion.bin.x86" 0xf778ebe0 in __kernel_vsyscall ()
  5    Thread 0xf3beeb40 (LWP 4078) "Bastion.bin.x86" 0xf778ebe0 in __kernel_vsyscall ()
  4    Thread 0xee019b40 (LWP 4079) "Bastion.bin.x86" 0xf778ebe0 in __kernel_vsyscall ()
  3    Thread 0xed79db40 (LWP 4080) "Bastion.bin.x86" 0xf778ebe0 in __kernel_vsyscall ()
  2    Thread 0xed57cb40 (LWP 4081) "Bastion.bin.x86" 0xf778ebe0 in __kernel_vsyscall ()
* 1    Thread 0xf6dd9740 (LWP 4074) "Bastion.bin.x86" 0xf778ebe0 in __kernel_vsyscall ()

Thread 8 (Thread 0xf58beb40 (LWP 4075)):
#0  0xf778ebe0 in __kernel_vsyscall ()
#1  0xf73d11ab in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/i386-linux-gnu/i686/cmov/libpthread.so.0
#2  0xf7680c44 in GC_wait_marker () at pthread_support.c:1863
#3  0xf7677aa4 in GC_help_marker (my_mark_no=16) at mark.c:1116
#4  0xf767f809 in GC_mark_thread (id=0x0) at pthread_support.c:552
#5  0xf73cc0cf in start_thread () from /lib/i386-linux-gnu/i686/cmov/libpthread.so.0
#6  0xf72f61ae in clone () from /lib/i386-linux-gnu/i686/cmov/libc.so.6

Thread 7 (Thread 0xf50bdb40 (LWP 4076)):
#0  0xf778ebe0 in __kernel_vsyscall ()
#1  0xf73d11ab in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/i386-linux-gnu/i686/cmov/libpthread.so.0
#2  0xf7680c44 in GC_wait_marker () at pthread_support.c:1863
#3  0xf7677aa4 in GC_help_marker (my_mark_no=16) at mark.c:1116
#4  0xf767f809 in GC_mark_thread (id=0x1) at pthread_support.c:552
#5  0xf73cc0cf in start_thread () from /lib/i386-linux-gnu/i686/cmov/libpthread.so.0
#6  0xf72f61ae in clone () from /lib/i386-linux-gnu/i686/cmov/libc.so.6

Thread 6 (Thread 0xf48bcb40 (LWP 4077)):
#0  0xf778ebe0 in __kernel_vsyscall ()
#1  0xf73d11ab in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/i386-linux-gnu/i686/cmov/libpthread.so.0
#2  0xf7680c44 in GC_wait_marker () at pthread_support.c:1863
#3  0xf7677aa4 in GC_help_marker (my_mark_no=16) at mark.c:1116
#4  0xf767f809 in GC_mark_thread (id=0x2) at pthread_support.c:552
#5  0xf73cc0cf in start_thread () from /lib/i386-linux-gnu/i686/cmov/libpthread.so.0
#6  0xf72f61ae in clone () from /lib/i386-linux-gnu/i686/cmov/libc.so.6

Thread 5 (Thread 0xf3beeb40 (LWP 4078)):
#0  0xf778ebe0 in __kernel_vsyscall ()
#1  0xf73d351c in do_futex_wait.constprop () from /lib/i386-linux-gnu/i686/cmov/libpthread.so.0
#2  0xf73d35e7 in __new_sem_wait_slow.constprop.1 () from /lib/i386-linux-gnu/i686/cmov/libpthread.so.0
#3  0xf765e5b0 in mono_sem_wait (sem=0xf7735dc8 <finalizer_sem>, alertable=1) at mono-semaphore.c:113
#4  0xf7590eb4 in finalizer_thread (unused=0x0) at gc.c:1066
#5  0xf761dbf8 in start_wrapper_internal (data=0x9ff9028) at threads.c:784
#6  start_wrapper (data=0x9ff9028) at threads.c:832
#7  0xf7651a5f in thread_start_routine (args=0x9fe7c8c) at wthreads.c:287
#8  0xf7680805 in GC_start_routine (arg=0x61fe0) at pthread_support.c:1468
#9  0xf73cc0cf in start_thread () from /lib/i386-linux-gnu/i686/cmov/libpthread.so.0
#10 0xf72f61ae in clone () from /lib/i386-linux-gnu/i686/cmov/libc.so.6

Thread 4 (Thread 0xee019b40 (LWP 4079)):
#0  0xf778ebe0 in __kernel_vsyscall ()
#1  0xf73d11ab in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/i386-linux-gnu/i686/cmov/libpthread.so.0
#2  0xf0db53ea in ?? () from /usr/lib/i386-linux-gnu/dri/r600_dri.so
#3  0xf0db49f5 in ?? () from /usr/lib/i386-linux-gnu/dri/r600_dri.so
#4  0xf73cc0cf in start_thread () from /lib/i386-linux-gnu/i686/cmov/libpthread.so.0
#5  0xf72f61ae in clone () from /lib/i386-linux-gnu/i686/cmov/libc.so.6

Thread 3 (Thread 0xed79db40 (LWP 4080)):
#0  0xf778ebe0 in __kernel_vsyscall ()
#1  0xf73d4c86 in nanosleep () from /lib/i386-linux-gnu/i686/cmov/libpthread.so.0
#2  0xf7650800 in SleepEx (ms=500, alertable=1) at wthreads.c:1027
#3  0xf7621be7 in monitor_thread (unused=0x0) at threadpool.c:777
#4  0xf761dbf8 in start_wrapper_internal (data=0xa6bdaf0) at threads.c:784
#5  start_wrapper (data=0xa6bdaf0) at threads.c:832
#6  0xf7651a5f in thread_start_routine (args=0x9fe8154) at wthreads.c:287
#7  0xf7680805 in GC_start_routine (arg=0x61f00) at pthread_support.c:1468
#8  0xf73cc0cf in start_thread () from /lib/i386-linux-gnu/i686/cmov/libpthread.so.0
#9  0xf72f61ae in clone () from /lib/i386-linux-gnu/i686/cmov/libc.so.6

Thread 2 (Thread 0xed57cb40 (LWP 4081)):
#0  0xf778ebe0 in __kernel_vsyscall ()
#1  0xf73d37ff in do_futex_wait () from /lib/i386-linux-gnu/i686/cmov/libpthread.so.0
#2  0xf73d3979 in __new_sem_wait_slow () from /lib/i386-linux-gnu/i686/cmov/libpthread.so.0
#3  0xf765e6a2 in mono_sem_timedwait (sem=0xf77364f4 <async_tp+20>, timeout_ms=2000, alertable=1) at mono-semaphore.c:76
#4  0xf76237af in async_invoke_thread (data=0x0) at threadpool.c:1485
#5  0xf761dbf8 in start_wrapper_internal (data=0xa6b33f8) at threads.c:784
#6  start_wrapper (data=0xa6b33f8) at threads.c:832
#7  0xf7651a5f in thread_start_routine (args=0x9fe81dc) at wthreads.c:287
#8  0xf7680805 in GC_start_routine (arg=0x61f00) at pthread_support.c:1468
#9  0xf73cc0cf in start_thread () from /lib/i386-linux-gnu/i686/cmov/libpthread.so.0
#10 0xf72f61ae in clone () from /lib/i386-linux-gnu/i686/cmov/libc.so.6

Thread 1 (Thread 0xf6dd9740 (LWP 4074)):
#0  0xf778ebe0 in __kernel_vsyscall ()
#1  0xf72eddcb in readv () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
#2  0xf7774bd6 in read () from /home/lumag/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so
#3  0xf750ba58 in mono_handle_native_sigsegv (signal=11, ctx=0xf7452b8c) at mini-exceptions.c:2208
#4  0xf75528b4 in mono_arch_handle_altstack_exception (sigctx=0xf7452b8c, fault_addr=0x3fc, stack_ovf=0) at exceptions-x86.c:1223
#5  0xf7482740 in mono_sigsegv_signal_handler (_dummy=11, info=0xf7452b0c, context=0xf7452b8c) at mini.c:5909
#6  <signal handler called>
#7  0xf7280b16 in free () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
#8  0xeb95b6d3 in snd_device_name_free_hint () from /home/lumag/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libasound.so.2
#9  0xeb95b916 in snd_device_name_hint () from /home/lumag/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libasound.so.2
#10 0xebaa3fa4 in ?? () from /home/lumag/.local/share/Steam/steamapps/common/Bastion/Linux/lib/libfmodex.so
#11 0xebaa4318 in ?? () from /home/lumag/.local/share/Steam/steamapps/common/Bastion/Linux/lib/libfmodex.so
#12 0xebaa4516 in ?? () from /home/lumag/.local/share/Steam/steamapps/common/Bastion/Linux/lib/libfmodex.so
#13 0xeba9e33b in ?? () from /home/lumag/.local/share/Steam/steamapps/common/Bastion/Linux/lib/libfmodex.so
#14 0xeba8f3c0 in FMOD::System::init(int, unsigned int, void*) () from /home/lumag/.local/share/Steam/steamapps/common/Bastion/Linux/lib/libfmodex.so
#15 0xecd6cbe4 in ?? ()
#16 0xecd6cb9c in ?? ()
#17 0xecd6c8b4 in ?? ()
#18 0xecd6c238 in ?? ()
#19 0xecd6b5a4 in ?? ()
#20 0xecd6b464 in ?? ()
#21 0xecd6ae8c in ?? ()
#22 0xecd6a0dc in ?? ()
#23 0xecd69db4 in ?? ()
#24 0xecd69ae0 in ?? ()
#25 0xecd69878 in ?? ()
#26 0xecd6983c in ?? ()
#27 0xed034b1b in ?? ()
#28 0xecd69448 in ?? ()
#29 0xecd68f70 in ?? ()
#30 0xecd68ea9 in ?? ()
#31 0xed0329f4 in ?? ()
#32 0xed0325a8 in ?? ()
#33 0xed03260f in ?? ()
#34 0xed03256a in ?? ()
#35 0xed032545 in ?? ()
#36 0xed032288 in ?? ()
#37 0xed032128 in ?? ()
#38 0xed030014 in ?? ()
#39 0xed02fd8c in ?? ()
#40 0xed02fcf0 in ?? ()
#41 0xed02e8d0 in ?? ()
#42 0xed79e88c in ?? ()
#43 0xed79e750 in ?? ()
#44 0xf3c5f304 in ?? ()
#45 0xf3c5f104 in ?? ()
#46 0xf3c5f207 in ?? ()
#47 0xf748a8da in mono_jit_runtime_invoke (method=0x9fa78c4, obj=0x0, params=0xffe7176c, exc=0x0) at mini.c:5791
#48 0xf75e9a20 in mono_runtime_invoke (method=0x9fa78c4, obj=0x0, params=0xffe7176c, exc=0x0) at object.c:2755
#49 0xf75eda72 in mono_runtime_exec_main (method=0x9fa78c4, args=0x3be00, exc=0x0) at object.c:3938
#50 0xf75f2970 in mono_runtime_run_main (method=0x9fa78c4, argc=0, argv=0x9fa27e8, exc=0x0) at object.c:3560
#51 0xf74e2582 in mono_jit_exec (domain=0x34e58, assembly=0x9ff5c30, argc=1, argv=0x9fa27e4) at driver.c:944
#52 0xf74e3e34 in main_thread_handler (user_data=<optimized out>) at driver.c:1003
#53 mono_main (argc=2, argv=0x9fa27e0) at driver.c:1855
#54 0x080491b3 in main (argc=1, argv=0xffe719d4) at kick.c:137

=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

/home/lumag/.local/share/Steam/steamapps/common/Bastion/Linux/run_steam.sh: line 10:  4074 Aborted                 ./Bastion.bin.x86 $@
Game removed: AppID 107100 "Bastion", ProcID 4074 
```

**Comment by Tele42** [comment]
Hello @lumag, since the game works when launched from outside steam, this is almost certainly a steam runtime incompatibility with your system libraries.

**Comment by lumag** [comment]
@Tele42 , thought so. Switching to 'Steam Beta' did not help. What else can
I do to debug/improve the situation?

**Comment by Tele42** [comment]
@lumag, you could try the <a href="https://wiki.archlinux.org/index.php/steam#Steam_runtime_issues">Arch workaround</a> and see if that helps at all.

**Comment by lumag** [comment]
@Tele42 Thanks for the pointer. LD_PRELOAD'ing host libasound.so.2 made
Bastion work.

For the reference: Linux 4.3, sound: HDA-Intel

**Comment by lumag** [comment]
Fixed in latest beta, thank you.
