### ISSUE TITLE
Crash on exit from Big Picture in libpthread with nvidia drivers

### ISSUE THREAD

**Issue by Tasssadar** [ValveSoftware/steam-for-linux#4407]
**OS:** Debian Testing (stretch) fully updated
**DE:** KDE5 with and without composition and LXDE
**Drivers:** Nvidia 361.42, but 352.79-5 from debian repo have the same issue

**Crash Ids:**
* CrashID=bp-2d375e35-dd9c-4f3a-9dbb-3ba4f2160415
* CrashID=bp-e1787386-78d6-46ac-8981-b99e22160415

Reproducible by entering Big Picture and then exiting it via the menu, by playing a game from big picture and then exiting and also by pressing the stick on steam controller (to open keyboard, doesn't work) and then the steam button on it (to enter big picture mode - crash is the same).

```
(gdb) bt full
#0  __GI___pthread_mutex_lock (mutex=0x80) at ../nptl/pthread_mutex_lock.c:68
        __PRETTY_FUNCTION__ = "__pthread_mutex_lock"
        type = <optimized out>
        id = <optimized out>
#1  0xf6bb0eeb in ?? () from /usr/lib/i386-linux-gnu/libGL.so.1
No symbol table info available.
#2  0xf5d549ef in ?? () from /usr/lib/i386-linux-gnu/libnvidia-glcore.so.361.42
No symbol table info available.
#3  0xf5b4986c in ?? () from /usr/lib/i386-linux-gnu/libnvidia-glcore.so.361.42
No symbol table info available.
#4  0xf5d52120 in ?? () from /usr/lib/i386-linux-gnu/libnvidia-glcore.so.361.42
No symbol table info available.
#5  0xf6bb4258 in ?? () from /usr/lib/i386-linux-gnu/libGL.so.1
No symbol table info available.
#6  0xf74232ce in start_thread (arg=0xf46c0b40) at pthread_create.c:334
        __res = <optimized out>
        pd = 0xf46c0b40
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {-146575360, 0, 4001536, -194247640, 937892267, 1803864493}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#7  0xf734d36e in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:122
No locals.
```

```Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected
    
Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  4001 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    Debian GNU/Linux testing (stretch) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.5.1-tyene+
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11803000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-release_2016-02-23
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 760/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 361.42
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x1187
    Number of Monitors:  1
    Number of Logical Video Cards:  2
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 20,08" x 11,42"  (23,07" diag)
                                            51,0cm x 29,0cm  (58,6cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 2048 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: Intel Haswell HDMI
    
Memory:
    RAM:  15915 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  cs_CZ.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  369943 Mb
    Largest Free Hard Disk Block:  163173 Mb
    VR Headset: None detected
    
    Fri Apr 15 18:44:21 2016 GMT: file ''/tmp/dumps/assert_20160415204335_1.dmp'', upload yes: ''CrashID=bp-e95575d8-c5dc-4611-a77d-1df2d2160415''
    Fri Apr 15 18:49:15 2016 GMT: file ''/tmp/dumps/assert_20160415204839_1.dmp'', upload yes: ''CrashID=bp-42847707-c030-422a-8cf8-5ac982160415''
    Fri Apr 15 18:50:19 2016 GMT: file ''/tmp/dumps/assert_20160415204922_1.dmp'', upload yes: ''CrashID=bp-8756dee9-7b5e-41dd-bd97-c1cd02160415''
    Fri Apr 15 18:54:20 2016 GMT: file ''/tmp/dumps/assert_20160415205240_1.dmp'', upload yes: ''CrashID=bp-10f8715e-c49d-4517-b452-b6af72160415''
    Fri Apr 15 19:02:47 2016 GMT: file ''/tmp/dumps/assert_20160415205957_1.dmp'', upload yes: ''CrashID=bp-fad07111-3706-471c-b66e-959d62160415''
    Fri Apr 15 19:20:37 2016 GMT: file ''/tmp/dumps/assert_20160415211955_1.dmp'', upload yes: ''CrashID=bp-7b1a0dc4-1363-49b5-a97e-b6a312160415''
    Fri Apr 15 19:25:40 2016 GMT: file ''/tmp/dumps/assert_20160415212501_1.dmp'', upload yes: ''CrashID=bp-b8a77c87-368a-4667-86fd-faad62160415''
    Fri Apr 15 19:28:20 2016 GMT: file ''/tmp/dumps/assert_20160415212643_1.dmp'', upload yes: ''CrashID=bp-2d375e35-dd9c-4f3a-9dbb-3ba4f2160415''
    Fri Apr 15 19:30:23 2016 GMT: file ''/tmp/dumps/assert_20160415212904_1.dmp'', upload yes: ''CrashID=bp-e1787386-78d6-46ac-8981-b99e22160415''
```

**Comment by Tasssadar** [comment]
Just noticed - setting __GL_THREADED_OPTIMIZATIONS=0 fixes this crash. I'm not sure whether it is on by default or not, if it isn't feel free to close this bug (although it'd be awesome if you'd be able to forward it to nvidia).

**Comment by cjwijtmans** [comment]
I have a similar setup and __GL_THREADED_OPTIMIZATIONS=1 is on for the entire system and steam does not crash. However i do get the crash with nvidia-settings (which i now launch with __GL_THREADED_OPTIMIZATIONS=0) also in libpthread.
