### ISSUE TITLE
Doesn't start on Ubuntu 16.04 | GTX 960m

### ISSUE THREAD

**Issue by moldcraft** [ValveSoftware/steam-for-linux#4605]
#### Your system information

* Steam client version: **1.0.0.52**
* Distribution (e.g. Ubuntu): **Ubuntu 16.04 x64**
* Opted into Steam client beta?: [Yes/No] **No**
* Have you checked for system updates?: [Yes/No] **Yes**

#### Please describe your issue in as much detail as possible:

I have installed a lot of of `*:i386` packages but nothing helps.

```
$ steam
Traceback (most recent call last):
  File "/usr/bin/steamdeps", line 419, in <module>
    sys.exit(main())
  File "/usr/bin/steamdeps", line 389, in main
    packages[ name ].setInstalled( match.group(2) )
KeyError: u'curl:i386'
Running Steam on ubuntu 16.04 64-bit
STEAM_RUNTIME is enabled automatically
/bin/bash: /home/i/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /bin/bash)
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
Installing breakpad exception handler for appid(steam)/version(1471977975)
Installing breakpad exception handler for appid(steam)/version(1471977975)
Installing breakpad exception handler for appid(steam)/version(1471977975)
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "unity-gtk-module"
Installing breakpad exception handler for appid(steam)/version(1471977975)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
[0825/001317:ERROR:main_delegate.cc(779)] Could not load cef_extensions.pak
[0825/001317:ERROR:browser_main_loop.cc(217)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
Installing breakpad exception handler for appid(steamwebhelper)/version(20160823182455)
Installing breakpad exception handler for appid(steamwebhelper)/version(1471976695)
[0825/001317:ERROR:main_delegate.cc(779)] Could not load cef_extensions.pak
Installing breakpad exception handler for appid(steamwebhelper)/version(20160823182455)
Installing breakpad exception handler for appid(steamwebhelper)/version(1471977975)
Installing breakpad exception handler for appid(steamwebhelper)/version(1471977975)
Installing breakpad exception handler for appid(steam)/version(1471977975)
Installing breakpad exception handler for appid(steam)/version(1471977975)
Installing breakpad exception handler for appid(steam)/version(1471977975)
Installing breakpad exception handler for appid(steam)/version(1471977975)
Installing breakpad exception handler for appid(steam)/version(1471977975)
Installing breakpad exception handler for appid(steam)/version(1471977975)
Created shared memory when not owner SteamController_Shared_mem
Installing breakpad exception handler for appid(steam)/version(1471977975)
Installing breakpad exception handler for appid(steam)/version(1471977975)

** (steam:6596): WARNING **: Unknown device type 14

** (steam:6596): WARNING **: Could not create object for /org/freedesktop/NetworkManager/Devices/1: unknown object type
Installing breakpad exception handler for appid(steam)/version(1471977975)

** (steam:6596): WARNING **: Ignoring invalid property 'secondaries'

** (steam:6596): WARNING **: Ignoring invalid property 'route-data'

** (steam:6596): WARNING **: Ignoring invalid property 'address-data'

** (steam:6596): WARNING **: Ignoring invalid property 'route-data'

** (steam:6596): WARNING **: Ignoring invalid property 'address-data'
Generating new string page texture 2: 48x256, total string texture memory is 49.15 KB
Generating new string page texture 3: 256x256, total string texture memory is 311.30 KB
Installing breakpad exception handler for appid(steam)/version(1471977975)
Installing breakpad exception handler for appid(steam)/version(1471977975)
^C
```

#### Steps for reproducing this issue:

1. Find a Dell XPS 15 9550 laptop
2. Install Ubuntu 16.04
3. Activate the nVidia 361.42 driver from **Additional Drivers** app
4. Install `steam`
5. Type `steam` in terminal

![screenshot from 2016-08-25 00-21-57](https://cloud.githubusercontent.com/assets/1475489/17948564/fcfdead2-6a59-11e6-91f2-9200ec1cfaef.png)

**Comment by gdrewb-valve** [comment]
You are likely hitting one of the Steam compatibility problems listed here, look at the other 16.04 issues open here.

**Comment by moldcraft** [comment]
https://github.com/ValveSoftware/steam-for-linux/issues/4424#issuecomment-242316735

**Comment by moldcraft** [comment]
Only on first start it took ~5 minutes, now every time it start fast.
