### ISSUE TITLE
Settings launcher of Amnesia can't start since latest Steam update

### ISSUE THREAD

**Issue by mtmkls** [ValveSoftware/steam-for-linux#4823]
#### Your system information

* Steam client version:
* Distribution (e.g. Ubuntu): Debian Unstable
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
If I start the launcher from the file manager, it shows its window immediately (but can't launch the game, because it can't connect to Steam). If I start the launcher from Steam, it creates a window, but doesn't draw anything into it, 100% CPU usage for a few seconds, and then nothing.

The main game can be started, but Justine can only be accessed from the launcher.

I connected to the process with gdb, and this is the backtrace during the first few seconds:
```
#0  0x00007f9164fca812 in XIfEvent () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#1  0x00007f9165301917 in XIfEvent () from /home/miki/.steam/ubuntu12_64/gameoverlayrenderer.so
#2  0x00007f9165003199 in ?? () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#3  0x00007f916500545b in _XimProtoOpenIM () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#4  0x00007f9165009591 in _XimOpenIM () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#5  0x00000000008c2122 in fl_handle(_XEvent const&) ()
#6  0x00000000008c2bf7 in fl_wait(double) ()
#7  0x00000000008a1ac2 in Fl::wait(double) ()
#8  0x00000000008a1cbd in Fl::run() ()
#9  0x00000000006bc19e in hplMain(std::string const&) ()
#10 0x000000000078d9e7 in main ()
```
This is the backtrace after it reaches the hang:
```
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007f91652ec8e5 in ?? () from /home/miki/.steam/ubuntu12_64/gameoverlayrenderer.so
#2  0x00007f91652f0bfa in ?? () from /home/miki/.steam/ubuntu12_64/gameoverlayrenderer.so
#3  0x00007f91652f0dc4 in ?? () from /home/miki/.steam/ubuntu12_64/gameoverlayrenderer.so
#4  0x00007f91652fcc7b in ?? () from /home/miki/.steam/ubuntu12_64/gameoverlayrenderer.so
#5  0x00007f9165301548 in XDestroyWindow () from /home/miki/.steam/ubuntu12_64/gameoverlayrenderer.so
#6  0x00007f91650125cf in ?? () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#7  0x00007f9165003b80 in ?? () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#8  0x00007f9165004b77 in ?? () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#9  0x00007f9164ff0210 in XCloseIM () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#10 0x00000000008c212f in fl_handle(_XEvent const&) ()
#11 0x00000000008c2bf7 in fl_wait(double) ()
#12 0x00000000008a1ac2 in Fl::wait(double) ()
#13 0x00000000008a1cbd in Fl::run() ()
#14 0x00000000006bc19e in hplMain(std::string const&) ()
#15 0x000000000078d9e7 in main ()
```

You may notice two things:
1. I removed libX11.so from the steam runtime, but it didn't fix the issue (I also removed libstdc++.so because your version conflicts with radeonsi_dri.so)
2. It hangs in gameoverlayrenderer.so, even though I disabled the steam overlay (the overlay gets properly disabled in the main game)

**Comment by mtmkls** [comment]
Workaround for Justine: set launch option "ptest".

**Comment by mtmkls** [comment]
It seems to be working fine now. Closing.
