### ISSUE TITLE
Steam client stop runnung after update

### ISSUE THREAD

**Issue by NTMan** [ValveSoftware/steam-for-linux#5105]
#### Your system information

* Steam client version (build number or date): How see it if client couldn't running
* Distribution (e.g. Ubuntu): Fedora
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

https://da.gd/N1uWD

**Comment by NTMan** [comment]
```
(gdb) bt
#0  0xef67d2ae in ?? () from /home/mikhail/.local/share/Steam/ubuntu12_32/steamclient.so
#1  0xeef35459 in ?? () from /home/mikhail/.local/share/Steam/ubuntu12_32/steamclient.so
#2  0xef2b87eb in ?? () from /home/mikhail/.local/share/Steam/ubuntu12_32/steamclient.so
#3  0xef2905c7 in ?? () from /home/mikhail/.local/share/Steam/ubuntu12_32/steamclient.so
#4  0xeee27684 in ?? () from /home/mikhail/.local/share/Steam/ubuntu12_32/steamclient.so
#5  0xef658457 in ?? () from /home/mikhail/.local/share/Steam/ubuntu12_32/steamclient.so
#6  0xf5b60f60 in ?? () from /home/mikhail/.local/share/Steam/ubuntu12_32/libvstdlib_s.so
#7  0xf5b61f9e in ?? () from /home/mikhail/.local/share/Steam/ubuntu12_32/libvstdlib_s.so
#8  0xf5b620df in Coroutine_Continue () from /home/mikhail/.local/share/Steam/ubuntu12_32/libvstdlib_s.so
#9  0xef658962 in ?? () from /home/mikhail/.local/share/Steam/ubuntu12_32/steamclient.so
#10 0xef66160e in ?? () from /home/mikhail/.local/share/Steam/ubuntu12_32/steamclient.so
#11 0xef662d2c in ?? () from /home/mikhail/.local/share/Steam/ubuntu12_32/steamclient.so
#12 0xef65ea58 in ?? () from /home/mikhail/.local/share/Steam/ubuntu12_32/steamclient.so
#13 0xef624e09 in ?? () from /home/mikhail/.local/share/Steam/ubuntu12_32/steamclient.so
#14 0xeec4ee99 in ?? () from /home/mikhail/.local/share/Steam/ubuntu12_32/steamclient.so
#15 0xef2731f1 in ?? () from /home/mikhail/.local/share/Steam/ubuntu12_32/steamclient.so
#16 0xeec511e9 in ?? () from /home/mikhail/.local/share/Steam/ubuntu12_32/steamclient.so
#17 0xeec52146 in ?? () from /home/mikhail/.local/share/Steam/ubuntu12_32/steamclient.so
#18 0xf5bbfed0 in SteamThreadTools::CThread::ThreadExceptionWrapper(void*) () from /home/mikhail/.local/share/Steam/ubuntu12_32/libtier0_s.so
#19 0xf5bbe21b in ?? () from /home/mikhail/.local/share/Steam/ubuntu12_32/libtier0_s.so
#20 0xf5bbe4ef in CatchAndWriteMiniDumpExForVoidPtrFn () from /home/mikhail/.local/share/Steam/ubuntu12_32/libtier0_s.so
#21 0xf5bbe541 in CatchAndWriteMiniDumpForVoidPtrFn () from /home/mikhail/.local/share/Steam/ubuntu12_32/libtier0_s.so
#22 0xf5bc2b61 in SteamThreadTools::CThread::ThreadProc(void*) () from /home/mikhail/.local/share/Steam/ubuntu12_32/libtier0_s.so
#23 0xf7c33307 in start_thread (arg=0xedfffb40) at pthread_create.c:465
#24 0xf79fd9f6 in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:108
```

**Comment by kisak-valve** [comment]
Hello @NTMan, this issue is already being tracked at #5101. You should be able to run `ln -s ${HOME}/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu/libdbus-1.so.3 ${HOME}/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_32/libdbus-1.so.3` to workaround this issue.

Closing as a duplicate.
