### ISSUE TITLE
Segfault in dbus_address_entry_get_value

### ISSUE THREAD

**Issue by kapsh** [ValveSoftware/steam-for-linux#5106]
#### Your system information

* Steam client version (build number or date): Jul 17 2017
* Distribution (e.g. Ubuntu): Gentoo
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. Launch Steam (big picture, steam controller).
2. Play game (reproducible with Shadow Tactics).
3. Steam crashes.

```

Thread 1 "steam" received signal SIGSEGV, Segmentation fault.
0xf0b91f74 in ?? ()
   from /home/kapsh/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu/libdbus-1.so.3
(gdb) backtrace
#0  0xf0b91f74 in ?? ()
   from /home/kapsh/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu/libdbus-1.so.3
#1  0xf0b6d4d1 in dbus_address_entry_get_value ()
   from /home/kapsh/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu/libdbus-1.so.3
#2  0xf0b8d145 in ?? ()
   from /home/kapsh/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu/libdbus-1.so.3
#3  0xf0b74c83 in ?? ()
   from /home/kapsh/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu/libdbus-1.so.3
#4  0xf0b70e06 in ?? ()
   from /home/kapsh/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu/libdbus-1.so.3
#5  0xf1f03d50 in ?? () from /home/kapsh/.local/share/Steam/ubuntu12_32/libSDL2-2.0.so.0
#6  0xf1f042e6 in ?? () from /home/kapsh/.local/share/Steam/ubuntu12_32/libSDL2-2.0.so.0
#7  0xf1f057c7 in ?? () from /home/kapsh/.local/share/Steam/ubuntu12_32/libSDL2-2.0.so.0
#8  0xf1f04797 in ?? () from /home/kapsh/.local/share/Steam/ubuntu12_32/libSDL2-2.0.so.0
#9  0xf1ef6335 in ?? () from /home/kapsh/.local/share/Steam/ubuntu12_32/libSDL2-2.0.so.0
#10 0xf1e7cf78 in ?? () from /home/kapsh/.local/share/Steam/ubuntu12_32/libSDL2-2.0.so.0
#11 0xf1e7cfce in ?? () from /home/kapsh/.local/share/Steam/ubuntu12_32/libSDL2-2.0.so.0
#12 0xf1e7d06a in ?? () from /home/kapsh/.local/share/Steam/ubuntu12_32/libSDL2-2.0.so.0
#13 0xf1e7760d in SDL_PollEvent () from /home/kapsh/.local/share/Steam/ubuntu12_32/libSDL2-2.0.so.0
#14 0xe85d9054 in ?? () from /home/kapsh/.local/share/Steam/ubuntu12_32/panorama/panorama.so
#15 0xe857a10c in ?? () from /home/kapsh/.local/share/Steam/ubuntu12_32/panorama/panorama.so
#16 0xe8556893 in ?? () from /home/kapsh/.local/share/Steam/ubuntu12_32/panorama/panorama.so
#17 0xf354185f in ?? () from /home/kapsh/.local/share/Steam/ubuntu12_32/steamui.so
#18 0xf3542f16 in ?? () from /home/kapsh/.local/share/Steam/ubuntu12_32/steamui.so
#19 0x5658c660 in RunSteam(int, char**, bool) ()
#20 0x5658d5f3 in ?? ()
#21 0x56578aac in ?? ()
#22 0xf7afc187 in __libc_start_main () from /lib32/libc.so.6
#23 0x5657c159 in _start ()
```

**Comment by kisak-valve** [comment]
Hello @kapsh, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
