### ISSUE TITLE
Client fails to start: fatal stalled cross-thread pipe

### ISSUE THREAD

**Issue by jandrewlong** [ValveSoftware/steam-for-linux#5899]
#### Your system information

* Steam client version (build number or date): 1541819448
* Distribution: Gentoo
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
The Steam client fails to start.  The auto-updater checks for updates, and downloads them, then the client window never appears.

The console output: https://gist.github.com/jandrewlong/32127ce253298cca54d9cc85de4a3937

```
../common/pipes.cpp (770) : Assertion Failed: fatal stalled cross-thread pipe
../common/pipes.cpp (770) : Assertion Failed: fatal stalled cross-thread pipe
../common/pipes.cpp (770) : Fatal assert failed: ../common/pipes.cpp, line 770.  Application exiting.

../common/pipes.cpp (770) : Fatal assert failed: ../common/pipes.cpp, line 770.  Application exiting.
```

#### Steps for reproducing this issue:

1. Try to launch Steam

**Comment by Pastafarianist** [comment]
This issue went away for me after I restarted the Steam client.

**Comment by jandrewlong** [comment]
When I `export PULSE_SERVER=/dev/null`, the steam client starts successfully.

**Comment by Seegras** [comment]
After the latest update, I got that thing too. Setting PULSE_SERVER=/dev/null doesn't help, and gdb output is pretty inconclusive: 

Fri May 15 2020 08:35:16.963210 - steam 1.12.2 startup with PID=240313, config=/home/user/.local/share/Steam/config, runtime=/opt/Games/Steam/SteamApps/common/SteamVR
Fri May 15 2020 08:35:16.963260 - vrclient type=VRApplication_SteamWatchdog
/data/src/common/pipes.cpp (770) : Assertion Failed: fatal stalled cross-thread pipe
/data/src/common/pipes.cpp (770) : Assertion Failed: fatal stalled cross-thread pipe
--Type <RET> for more, q to quit, c to continue without paging--
 continue without paging--
Thread 1 "steam" received signal SIGTRAP, Trace/breakpoint trap.
0xed75f5fd in ?? () from /home/user/.local/share/Steam/ubuntu12_32/steamclient.so
(gdb) 
(gdb) bt
#0  0xed75f5fd in  () at /home/user/.local/share/Steam/ubuntu12_32/steamclient.so
#1  0xed75f8c9 in  () at /home/user/.local/share/Steam/ubuntu12_32/steamclient.so
#2  0xed750fa8 in  () at /home/user/.local/share/Steam/ubuntu12_32/steamclient.so
#3  0xed381d9e in  () at /home/user/.local/share/Steam/ubuntu12_32/steamclient.so
#4  0xf2b8ab0f in  () at /home/user/.local/share/Steam/ubuntu12_32/steamui.so
#5  0xf2b7775a in  () at /home/user/.local/share/Steam/ubuntu12_32/steamui.so
#6  0xf2ab8d74 in  () at /home/user/.local/share/Steam/ubuntu12_32/steamui.so
#7  0x56590c60 in RunSteam(int, char**, bool) ()
#8  0x56591be3 in  ()
#9  0x565799ac in  ()
#10 0xf79b4ef1 in __libc_start_main () at /lib/i386-linux-gnu/libc.so.6
#11 0x5657e0b9 in _start ()

**Comment by Mubelotix** [comment]
It happened to me on Ubuntu 21.10. You might want to change that label

**Comment by happysmash27** [comment]
This suddenly started happening to me, too, also on Gentoo, oddly enough, opted in to the Steam client beta. I've been updating my system a lot lately so would think it is a system update except, well, the issue started in 2018, and I certainly did not have this issue back in 2018.

**Comment by MrKich** [comment]
Suddenly started to happen to me on ubuntu 22.04.
Running "PULSE_SERVER=/dev/null steam" solves problem with launching steam, but removes sound from games.

**Comment by agturcz** [comment]
The problem still exists. This is from Oxygen Not Included, unity Player.log
```
src/common/pipes.cpp (883) : fatal stalled cross-thread pipe.
/data/src/common/pipes.cpp 883 fatal stalled cross-thread pipe.Caught fatal signal - signo:5 code:128 errno:0 addr:(nil)
Obtained 34 stack frames.
#0  0x007f3a1a8c8f9d in Breakpad_SteamWriteMiniDumpUsingExceptionInfoWithBuildId
#1  0x007f3a1a751a9e in Steam_ReleaseThreadLocalMemory
#2  0x007f3bc0157bb6 in SteamAPI_Init
#3  0x000000404e74a7 in (wrapper managed-to-native) Steamworks.NativeMethods:SteamAPI_Init ()
```

**Comment by kisak-valve** [comment]
Hello @agturcz, if your issue is with running Oxygen Not Included and not with starting the Steam client, then it should be evaluated separately. Please open a new issue report.

**Comment by MrKich** [comment]
Actually fixed all problems with steam (there was not only sound issues for me, but oom-killer and shader issues, too).

The source of problems was that I had an invalid config in /etc/security/limits.conf file:
```
* soft stack 1048576
* hard stack 1048576
```

This sets default stack size for threads to 1Gb (so, for 32-bit environment like steam, you could only have 4 threads with default stack size).

Don't know when I added this two lines to config, but after removing them, everything is working again.

**Comment by MrKich** [comment]
Distro is ubuntu 22.04

/etc/security/limits.conf works as usual (and file exists).

> Also, it's unusual for a limit that's "too high" prevent things from running correctly, it's usually the ones that are too low that have this effect.

Yep, but with 32-bit applications like steam with only 4Gb ram available it is possible :)

**Comment by user1-github** [comment]
I understand this issue might be caused by some specific distro configuration?

I use Steam Flatpak on Debian 12.1.0 and it crashes during game downloads. It causes my Steam client window to stop responding and then my Gnome Wayland session freezes. Since I didn't experience this issue with Steam Flatpak on other distros, I now suspect this might be caused by some configuration in Debian.
