### ISSUE TITLE
Steam crash while playing CSGO

### ISSUE THREAD

**Issue by djdeath** [ValveSoftware/steam-for-linux#6717]
#### Your system information

* Steam client version (build number or date): Nov 20 2019, at 01:49:33, 1574216296
* Distribution (e.g. Ubuntu): Ubuntu 19.10
* Opted into Steam client beta?: No
* Have you checked for system updates?: [Yes/No]

#### Please describe your issue in as much detail as possible:

While playing CSGO, the game suddenly exited and the steam UI was gone.
Got a backtrace from coredumpd : 
```
Core was generated by `/home/djdeath/.steam/ubuntu12_32/steam'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0xf7a36130 in ?? () from /lib/i386-linux-gnu/libc.so.6
[Current thread is 1 (Thread 0xf7865dc0 (LWP 2369))]
(gdb) bt
#0  0xf7a36130 in ?? () from /lib/i386-linux-gnu/libc.so.6
#1  0xf3f39258 in ?? () from /home/djdeath/.steam/ubuntu12_32/steam-runtime/pinned_libs_32/libdbus-1.so.3
#2  0xf3f3968a in ?? () from /home/djdeath/.steam/ubuntu12_32/steam-runtime/pinned_libs_32/libdbus-1.so.3
#3  0xf3f383fb in ?? () from /home/djdeath/.steam/ubuntu12_32/steam-runtime/pinned_libs_32/libdbus-1.so.3
#4  0xf3f2365c in ?? () from /home/djdeath/.steam/ubuntu12_32/steam-runtime/pinned_libs_32/libdbus-1.so.3
#5  0xf3f20802 in ?? () from /home/djdeath/.steam/ubuntu12_32/steam-runtime/pinned_libs_32/libdbus-1.so.3
#6  0xf3f211a8 in ?? () from /home/djdeath/.steam/ubuntu12_32/steam-runtime/pinned_libs_32/libdbus-1.so.3
#7  0xf3f25b51 in ?? () from /home/djdeath/.steam/ubuntu12_32/steam-runtime/pinned_libs_32/libdbus-1.so.3
#8  0xf3f27b66 in dbus_message_iter_append_basic () from /home/djdeath/.steam/ubuntu12_32/steam-runtime/pinned_libs_32/libdbus-1.so.3
#9  0xf3f297c0 in dbus_message_new_error () from /home/djdeath/.steam/ubuntu12_32/steam-runtime/pinned_libs_32/libdbus-1.so.3
#10 0xf3f2ca34 in ?? () from /home/djdeath/.steam/ubuntu12_32/steam-runtime/pinned_libs_32/libdbus-1.so.3
#11 0xf3f1b6b4 in dbus_connection_send_with_reply () from /home/djdeath/.steam/ubuntu12_32/steam-runtime/pinned_libs_32/libdbus-1.so.3
#12 0xf3f1b9a3 in dbus_connection_send_with_reply_and_block ()
   from /home/djdeath/.steam/ubuntu12_32/steam-runtime/pinned_libs_32/libdbus-1.so.3
#13 0xf47ea472 in ?? () from /home/djdeath/.steam/ubuntu12_32/libSDL2-2.0.so.0
#14 0xf47eac96 in ?? () from /home/djdeath/.steam/ubuntu12_32/libSDL2-2.0.so.0
#15 0xf47eb01f in ?? () from /home/djdeath/.steam/ubuntu12_32/libSDL2-2.0.so.0
#16 0xf47dccbe in ?? () from /home/djdeath/.steam/ubuntu12_32/libSDL2-2.0.so.0
#17 0xf47aa767 in ?? () from /home/djdeath/.steam/ubuntu12_32/libSDL2-2.0.so.0
#18 0xf472940e in SDL_DisableScreenSaver () from /home/djdeath/.steam/ubuntu12_32/libSDL2-2.0.so.0
#19 0xf317218a in ?? () from /home/djdeath/.steam/ubuntu12_32/steamui.so
#20 0xf3173d0e in ?? () from /home/djdeath/.steam/ubuntu12_32/steamui.so
#21 0x565db190 in RunSteam(int, char**, bool) ()
#22 0x565dc106 in ?? ()
#23 0x565c54bc in ?? ()
#24 0xf7901fb9 in __libc_start_main () from /lib/i386-linux-gnu/libc.so.6
#25 0x565c9289 in _start ()
(gdb) 

```

#### Steps for reproducing this issue:

It happened fairly randomly, no particular step...

**Comment by DadouLapous** [comment]
Same issue with 
    Steam client version (build number or date): 1575606714
    Distribution (e.g. Ubuntu): Archlinux
    Opted into Steam client beta?: Yes
    Have you checked for system updates?: Yes

**Comment by djdeath** [comment]
> Hello @djdeath, @DavidLapous, are either of you still experiencing this issue on an up to date system?

I managed to get rid of the issue by applying some of the suggestion on this issue : https://github.com/ValveSoftware/csgo-osx-linux/issues/2651#issuecomment-962948577 (replace tcmalloc with the system lib).

**Comment by DavidLapous** [comment]
No, I haven't encountered this issue for a long time (1+year at least), and I've changed laptops since then.

**Comment by kisak-valve** [comment]
Thanks for retesting, closing as outdated.
