### ISSUE TITLE
New SteamVR version 1.15.1 (1601587350) segfaults in  std::string::compare, traceback included

### ISSUE THREAD

**Issue by yasarabio** [ValveSoftware/steam-for-linux#7381]
#### Your system information

* Steam client version:  (build number or date): 
* Distribution (e.g. Ubuntu): CentOS 7
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: No

#### Please describe your issue in as much detail as possible:

When starting SteamVR, I get a segmentation fault with this traceback, which indicates that function "IsRunningInAppContainer" does something wrong:

[kornel@yasara2 bin]$ gdb linux64/vrstartup core.3757
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-115.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /home/kornel/.steam/steamapps/common/SteamVR/bin/linux64/vrstartup...Missing separate debuginfo for /home/kornel/.steam/steamapps/common/SteamVR/bin/linux64/vrstartup
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/53/ab58a7e42ce4e8aa6894425f03a0d5fc4f304a.debug
(no debugging symbols found)...done.
[New LWP 3757]
Missing separate debuginfo for /home/kornel/.steam/steamapps/common/SteamVR/bin/linux64/libSDL2-2.0.so.0
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/fe/82171601f25f8fcf56f84ccda5714a0e2c88cb.debug
Missing separate debuginfo for /home/kornel/.steam/steamapps/common/SteamVR/bin/linux64/libopenvr_api.so
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/59/62fc5d74dd927360506bced709293d0606cc7a.debug
Missing separate debuginfo for /home/kornel/.steam/steamapps/common/SteamVR/bin/linux64/libsteam_api.so
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/11/1902389643b15beee454d61fecc94ed68a83a7.debug
Missing separate debuginfo for /home/kornel/.steam/ubuntu12_32/steam-runtime/pinned_libs_64/libstdc++.so.6
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/24/302938237b8f927e3a524231f4722ae6c503b0.debug
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Missing separate debuginfo for /home/kornel/.steam/linux64/steamclient.so
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/e2/32bccc8c0a7097e36c148fa722c49f18118407.debug
Missing separate debuginfo for /home/kornel/.steam/linux64/crashhandler.so
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/c6/98b3dc98acb79d0b7ddb0f3221de3950502849.debug
Missing separate debuginfo for /home/kornel/.steam/steamapps/common/SteamVR/bin/linux64/vrclient.so
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/9f/8abbf0efdedf253490061d19ac1a6dd994fdc8.debug
Core was generated by `/home/kornel/.steam/steamapps/common/SteamVR/bin/linux64/vrstartup'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f0eda9e919d in std::string::compare(char const*) const () from /home/kornel/.steam/ubuntu12_32/steam-runtime/pinned_libs_64/libstdc++.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.17-292.el7.x86_64 libX11-1.6.7-2.el7.x86_64 libXau-1.0.8-2.1.el7.x86_64 libXext-1.3.3-3.el7.x86_64 libgcc-4.8.5-39.el7.x86_64 libglvnd-1.0.1-0.8.git5baa1e5.el7.x86_64 libglvnd-glx-1.0.1-0.8.git5baa1e5.el7.x86_64 libxcb-1.13-1.el7.x86_64
(gdb) where
#0  0x00007f0eda9e919d in std::string::compare(char const*) const () from /home/kornel/.steam/ubuntu12_32/steam-runtime/pinned_libs_64/libstdc++.so.6
#1  0x00007f0ed7bb80f2 in IsRunningInAppContainer() () from /home/kornel/.steam/steamapps/common/SteamVR/bin/linux64/vrclient.so
#2  0x00007f0ed7b51c39 in CHmdSystemLatest::Init(vr::EVRApplicationType, char const*) () from /home/kornel/.steam/steamapps/common/SteamVR/bin/linux64/vrclient.so
#3  0x00007f0edbacb0d2 in VR_InitInternal2 () from /home/kornel/.steam/steamapps/common/SteamVR/bin/linux64/libopenvr_api.so
#4  0x0000000000407bcf in RealMain(int, char**) ()
#5  0x0000000000409470 in main ()

**Comment by yasarabio** [comment]
The steam client version is 1601512230
