### ISSUE TITLE
CSGO crashes with SEGV in tcmalloc::CentralFreeList::FetchFromSpans()

### ISSUE THREAD

**Issue by 31KM** [ValveSoftware/steam-for-linux#8051]
#### Your system information

* Steam client version (build number or date): 1.0.0.72-1
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: Yes and no - issue happens with both
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Start CSGO, following exception happens:
```
Thread 1 "csgo_linux64" received signal SIGSEGV, Segmentation fault.
0x00007ffff7d882b7 in tcmalloc::CentralFreeList::FetchFromSpans() ()
   from /media/ssd/steamlib_ssd/steamapps/common/Counter-Strike Global Offensive/bin/linux64/libtcmalloc_minimal.so.0
#0  0x00007ffff7d882b7 in tcmalloc::CentralFreeList::FetchFromSpans() ()
   from /media/ssd/steamlib_ssd/steamapps/common/Counter-Strike Global Offensive/bin/linux64/libtcmalloc_minimal.so.0
#1  0x00007ffff7d88627 in tcmalloc::CentralFreeList::RemoveRange(void**, void**, int) ()
   from /media/ssd/steamlib_ssd/steamapps/common/Counter-Strike Global Offensive/bin/linux64/libtcmalloc_minimal.so.0
#2  0x00007ffff7d8b15d in tcmalloc::ThreadCache::FetchFromCentralCache(unsigned long, unsigned long) ()
   from /media/ssd/steamlib_ssd/steamapps/common/Counter-Strike Global Offensive/bin/linux64/libtcmalloc_minimal.so.0
#3  0x00007ffff7d92076 in tc_new () from /media/ssd/steamlib_ssd/steamapps/common/Counter-Strike Global Offensive/bin/linux64/libtcmalloc_minimal.so.0
#4  0x00007fffdd9fb1b4 in SteamThreadTools::CThread::Start (this=0x2d29c600, nBytesStack=<optimized out>) at threadtools.cpp:3318
#5  0x00007fffdd9db8ef in CVideoPlayerManager::Init (this=0x1e0b7d80) at ../common/video/videoplayermanager.cpp:164
#6  0x00007fffdd9dbf9d in CVideoPlayerManager::AddPlayerToThreadPool (this=0x1e0b7d80, pPlayer=0x2bd97680) at ../common/video/videoplayermanager.cpp:252
#7  0x00007fffd0944c43 in ?? () from /media/ssd/steamlib_ssd/steamapps/common/Counter-Strike Global Offensive/csgo/bin/linux64/client_client.so
#8  0x00007fffd0948378 in ?? () from /media/ssd/steamlib_ssd/steamapps/common/Counter-Strike Global Offensive/csgo/bin/linux64/client_client.so
#9  0x00007fffd094858e in ?? () from /media/ssd/steamlib_ssd/steamapps/common/Counter-Strike Global Offensive/csgo/bin/linux64/client_client.so
#10 0x00007fffdc08cc0d in ?? () from /media/ssd/steamlib_ssd/steamapps/common/Counter-Strike Global Offensive/bin/linux64/panorama_client.so
#11 0x00007fffdc08e85b in ?? () from /media/ssd/steamlib_ssd/steamapps/common/Counter-Strike Global Offensive/bin/linux64/panorama_client.so
#12 0x00007fffdc08cc65 in ?? () from /media/ssd/steamlib_ssd/steamapps/common/Counter-Strike Global Offensive/bin/linux64/panorama_client.so
#13 0x00007fffdc08e85b in ?? () from /media/ssd/steamlib_ssd/steamapps/common/Counter-Strike Global Offensive/bin/linux64/panorama_client.so
#14 0x00007fffdc08cc65 in ?? () from /media/ssd/steamlib_ssd/steamapps/common/Counter-Strike Global Offensive/bin/linux64/panorama_client.so
#15 0x00007fffdc08e85b in ?? () from /media/ssd/steamlib_ssd/steamapps/common/Counter-Strike Global Offensive/bin/linux64/panorama_client.so
#16 0x00007fffdc08cc65 in ?? () from /media/ssd/steamlib_ssd/steamapps/common/Counter-Strike Global Offensive/bin/linux64/panorama_client.so
#17 0x00007fffdc08e85b in ?? () from /media/ssd/steamlib_ssd/steamapps/common/Counter-Strike Global Offensive/bin/linux64/panorama_client.so
#18 0x00007fffdc08cc65 in ?? () from /media/ssd/steamlib_ssd/steamapps/common/Counter-Strike Global Offensive/bin/linux64/panorama_client.so
#19 0x00007fffdc08d178 in ?? () from /media/ssd/steamlib_ssd/steamapps/common/Counter-Strike Global Offensive/bin/linux64/panorama_client.so
#20 0x00007fffdc08d637 in ?? () from /media/ssd/steamlib_ssd/steamapps/common/Counter-Strike Global Offensive/bin/linux64/panorama_client.so
#21 0x00007fffdc077af8 in ?? () from /media/ssd/steamlib_ssd/steamapps/common/Counter-Strike Global Offensive/bin/linux64/panorama_client.so
#22 0x00007fffd046ae79 in ?? () from /media/ssd/steamlib_ssd/steamapps/common/Counter-Strike Global Offensive/csgo/bin/linux64/client_client.so
#23 0x00007fffd046b7f5 in ?? () from /media/ssd/steamlib_ssd/steamapps/common/Counter-Strike Global Offensive/csgo/bin/linux64/client_client.so
#24 0x00007fffdc08e96a in ?? () from /media/ssd/steamlib_ssd/steamapps/common/Counter-Strike Global Offensive/bin/linux64/panorama_client.so
#25 0x00007fffdc08cc65 in ?? () from /media/ssd/steamlib_ssd/steamapps/common/Counter-Strike Global Offensive/bin/linux64/panorama_client.so
#26 0x00007fffdc08d178 in ?? () from /media/ssd/steamlib_ssd/steamapps/common/Counter-Strike Global Offensive/bin/linux64/panorama_client.so
#27 0x00007fffdc08d637 in ?? () from /media/ssd/steamlib_ssd/steamapps/common/Counter-Strike Global Offensive/bin/linux64/panorama_client.so
#28 0x00007fffd04002eb in ?? () from /media/ssd/steamlib_ssd/steamapps/common/Counter-Strike Global Offensive/csgo/bin/linux64/client_client.so
#29 0x00007fffd040035f in ?? () from /media/ssd/steamlib_ssd/steamapps/common/Counter-Strike Global Offensive/csgo/bin/linux64/client_client.so
#30 0x00007fffdc08e96a in ?? () from /media/ssd/steamlib_ssd/steamapps/common/Counter-Strike Global Offensive/bin/linux64/panorama_client.so
#31 0x00007fffdc08cc65 in ?? () from /media/ssd/steamlib_ssd/steamapps/common/Counter-Strike Global Offensive/bin/linux64/panorama_client.so
#32 0x00007fffdc08d178 in ?? () from /media/ssd/steamlib_ssd/steamapps/common/Counter-Strike Global Offensive/bin/linux64/panorama_client.so
#33 0x00007fffdc08d637 in ?? () from /media/ssd/steamlib_ssd/steamapps/common/Counter-Strike Global Offensive/bin/linux64/panorama_client.so
#34 0x00007fffd03423db in ?? () from /media/ssd/steamlib_ssd/steamapps/common/Counter-Strike Global Offensive/csgo/bin/linux64/client_client.so
#35 0x00007fffe5a9d526 in ?? () from /media/ssd/steamlib_ssd/steamapps/common/Counter-Strike Global Offensive/bin/linux64/engine_client.so
#36 0x00007fffe5aa112d in ?? () from /media/ssd/steamlib_ssd/steamapps/common/Counter-Strike Global Offensive/bin/linux64/engine_client.so
#37 0x00007fffe5b230b0 in ?? () from /media/ssd/steamlib_ssd/steamapps/common/Counter-Strike Global Offensive/bin/linux64/engine_client.so
#38 0x00007fffe5b28704 in ?? () from /media/ssd/steamlib_ssd/steamapps/common/Counter-Strike Global Offensive/bin/linux64/engine_client.so
#39 0x00007fffe5b250fc in ?? () from /media/ssd/steamlib_ssd/steamapps/common/Counter-Strike Global Offensive/bin/linux64/engine_client.so
#40 0x00007fffe5d19389 in ?? () from /media/ssd/steamlib_ssd/steamapps/common/Counter-Strike Global Offensive/bin/linux64/engine_client.so
#41 0x00007fffe5b26c9c in ?? () from /media/ssd/steamlib_ssd/steamapps/common/Counter-Strike Global Offensive/bin/linux64/engine_client.so
#42 0x00007ffff75aa609 in ?? () from bin/linux64/launcher_client.so
#43 0x00007ffff75aa609 in ?? () from bin/linux64/launcher_client.so
#44 0x00007ffff7581a5b in LauncherMain () from bin/linux64/launcher_client.so
#45 0x00007ffff7ba9b25 in __libc_start_main () from /usr/lib/libc.so.6
#46 0x000000000040079d in _start ()
```
The game starts, the screen goes black and after ~10s the game closes.

#### Steps for reproducing this issue:
1.  Start CSGO

Tried with "stock" and native runtime. Also reinstalled steam and checked integrity of game files. If you need more info I will gladly add them.

**Comment by kisak-valve** [comment]
Hello @31KM, we're tracking issues with CS:GO in the [csgo-osx-linux](https://github.com/ValveSoftware/csgo-osx-linux/issues/) issue tracker, and this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/2659.

Since this issue report potentially adds some additional insight, I've gone ahead and transferred it to https://github.com/ValveSoftware/csgo-osx-linux/issues/2659#issuecomment-916458773. Closing in favor of the older issue report.
