### ISSUE TITLE
Game cannot launch from secondary hard drive

### ISSUE THREAD

**Issue by irlcatgirl** [ValveSoftware/steam-for-linux#8099]
#### Your system information

* Steam client version (build number or date): Unsure
* Distribution (e.g. Ubuntu): Ubuntu 21.04
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Steam fails to access a harddrive other than the C drive.
```
catgirl@CATGIRL:~$ steam
Running Steam on ubuntu 21.04 64-bit
STEAM_RUNTIME is enabled automatically
Steam runtime environment up-to-date!
Steam client's requirements are satisfied
WARNING: Using default/fallback debugger launch
/home/catgirl/.local/share/Steam/ubuntu12_32/steam
[2021-09-23 12:23:54] Startup - updater built Sep 17 2021 04:27:28
Installing breakpad exception handler for appid(steam)/version(1631912732)
[2021-09-23 12:23:54] Loading cached metrics from disk (/home/catgirl/.local/share/Steam/package/steam_client_metrics.bin)
[2021-09-23 12:23:54] Using the following download hosts for Public, Realm steamglobal
[2021-09-23 12:23:54] 1. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 100, source = 'update_hosts_cached.vdf'
[2021-09-23 12:23:54] 2. https://cdn.akamai.steamstatic.com, /client/, Realm 'steamglobal', weight was 100, source = 'update_hosts_cached.vdf'
[2021-09-23 12:23:54] 3. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
Installing breakpad exception handler for appid(steam)/version(1631912732)
[2021-09-23 12:23:54] Verifying installation...
[2021-09-23 12:23:54] Verification complete
Loaded SDL version 2.0.17-6744061
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"

(steam:27301): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Yaru-dark/gtk-2.0/main.rc:775: error: unexpected identifier `direction', expected character `}'

(steam:27301): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Yaru-dark/gtk-2.0/hacks.rc:28: error: invalid string constant "normal_entry", expected valid string constant
Installing breakpad exception handler for appid(steam)/version(1631912732)
Fontconfig warning: line 5: unknown element "its:rules"
Fontconfig warning: line 6: unknown element "its:translateRule"
Fontconfig warning: line 9: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 8: unknown element "description"
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 76: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 76: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 84: saw unknown, expected number
Fontconfig warning: "/etc/fonts/conf.d/11-lcdfilter-default.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/11-lcdfilter-default.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/11-lcdfilter-default.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 8: unknown element "description"
Runtime for steamwebhelper: defaulting to /home/catgirl/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 8: unknown element "description"
+ exec /home/catgirl/.local/share/Steam/ubuntu12_64/steam-runtime-heavy.sh --unpack-dir=/home/catgirl/.local/share/Steam/ubuntu12_64 --runtime=steam-runtime-heavy -- ./steamwebhelper -lang=en_US -cachedir=/home/catgirl/.local/share/Steam/config/htmlcache -steampid=27301 -buildid=1631912732 -steamid=0 -cachedir=/home/catgirl/.local/share/Steam/config/htmlcache -steamuniverse=Public -realm=Global -clientui=/home/catgirl/.local/share/Steam/clientui --enable-blink-features=ResizeObserver,Worklet,AudioWorklet --enable-media-stream --enable-smooth-scrolling --password-store=basic --log-file=/home/catgirl/.local/share/Steam/logs/cef_log.txt --disable-quick-menu
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/65-fonts-persian.conf", line 34: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/65-fonts-persian.conf", line 35: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/69-unifont.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/69-unifont.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/70-no-bitmaps.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/70-no-bitmaps.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/70-no-bitmaps.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/80-delicious.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/80-delicious.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/90-synthetic.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/90-synthetic.conf", line 5: unknown element "its:translateRule"
Could not connect to X session manager: None of the authentication protocols specified are supported
Installing breakpad exception handler for appid(steam)/version(1631912732)
Installing breakpad exception handler for appid(steam)/version(1631912732)
Installing breakpad exception handler for appid(steam)/version(1631912732)
Installing breakpad exception handler for appid(steam)/version(1631912732)
Installing breakpad exception handler for appid(steam)/version(1631912732)
Installing breakpad exception handler for appid(steam)/version(1631912732)
Installing breakpad exception handler for appid(steam)/version(1631912732)
Installing breakpad exception handler for appid(steam)/version(1631912732)
Installing breakpad exception handler for appid(steam)/version(1631912732)
CAppInfoCacheReadFromDiskThread took 15 milliseconds to initialize
Installing breakpad exception handler for appid(steam)/version(1631912732)
Installing breakpad exception handler for appid(steam)/version(1631912732)
Installing breakpad exception handler for appid(steam)/version(1631912732)
Installing breakpad exception handler for appid(steam)/version(1631912732)
Proceed to auto login
Installing breakpad exception handler for appid(steam)/version(1631912732)
Could not connect to X session manager: None of the authentication protocols specified are supported
Opted-in Controller Mask for AppId 0: 0
Could not connect to X session manager: None of the authentication protocols specified are supported
Installing breakpad exception handler for appid(steam)/version(1631912732)
Installing breakpad exception handler for appid(steam)/version(1631912732)

(steam:27301): Gtk-WARNING **: gtk_disable_setlocale() must be called before gtk_init()
Installing breakpad exception handler for appid(steam)/version(1631912732)
Installing breakpad exception handler for appid(steam)/version(1631912732)
Installing breakpad exception handler for appid(steam)/version(1631912732)
roaming config store loaded successfully - 380 bytes.
migrating temporary roaming config store
BRefreshApplicationsInLibrary 1: 3ms
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Installing breakpad exception handler for appid(steam)/version(1631912732)
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Failed to init SteamVR because it isn't installed
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
ExecCommandLine: "'/home/catgirl/.local/share/Steam/ubuntu12_32/steam'"
System startup time: 2.89 seconds
BuildCompleteAppOverviewChange: 117
RegisterForAppOverview 1: 3ms
RegisterForAppOverview 2: 3ms
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Installing breakpad exception handler for appid(steam)/version(1631912732)
Installing breakpad exception handler for appid(steam)/version(1631912732)
[1113000]Non-Steam Controller Configs Enabled: 1
Installing breakpad exception handler for appid(steam)/version(1631912732)
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
GameAction [AppID 1113000, ActionID 1] : LaunchApp changed task to ProcessingInstallScript with ""
Traceback (most recent call last):
  File "/usr/lib/python3.7/tarfile.py", line 2206, in makelink
    os.symlink(tarinfo.linkname, targetpath)
OSError: [Errno 22] Invalid argument: '../drive_c' -> '/media/catgirl/Seagate HDD/SteamLibrary/steamapps/common/Proton 6.3/dist/./share/default_pfx/dosdevices/c:'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/catgirl/Seagate HDD/SteamLibrary/steamapps/common/Proton 6.3/proton", line 1253, in <module>
    g_proton.extract_tarball()
  File "/media/catgirl/Seagate HDD/SteamLibrary/steamapps/common/Proton 6.3/proton", line 318, in extract_tarball
    tar.extractall(path=self.dist_dir)
  File "/usr/lib/python3.7/tarfile.py", line 2004, in extractall
    numeric_owner=numeric_owner)
  File "/usr/lib/python3.7/tarfile.py", line 2046, in extract
    numeric_owner=numeric_owner)
  File "/usr/lib/python3.7/tarfile.py", line 2124, in _extract_member
    self.makelink(tarinfo, targetpath)
  File "/usr/lib/python3.7/tarfile.py", line 2217, in makelink
    targetpath)
  File "/usr/lib/python3.7/tarfile.py", line 2118, in _extract_member
    self.makedir(tarinfo, targetpath)
  File "/usr/lib/python3.7/tarfile.py", line 2147, in makedir
    os.mkdir(targetpath, 0o700)
OSError: [Errno 22] Invalid argument: '/media/catgirl/Seagate HDD/SteamLibrary/steamapps/common/Proton 6.3/dist/./share/default_pfx/dosdevices/c:'
GameAction [AppID 1113000, ActionID 1] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 1113000, ActionID 1] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 1113000, ActionID 1] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 1113000, ActionID 1] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 1113000, ActionID 1] : LaunchApp continues with user response "CreatingProcess"
Opted-in Controller Mask for AppId 1113000: fffc
/bin/sh\0-c\0/home/catgirl/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=1113000 -- '/media/catgirl/Seagate HDD/SteamLibrary/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/media/catgirl/Seagate HDD/SteamLibrary/steamapps/common/Proton 6.3'/proton waitforexitandrun  '/media/catgirl/Seagate HDD/SteamLibrary/steamapps/common/Persona 4 Golden/P4G.exe'\0
Game update: AppID 1113000 "", ProcID 28347, IP 0.0.0.0:0
ERROR: ld.so: object '/home/catgirl/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/catgirl/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/catgirl/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/catgirl/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/catgirl/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 28352 != 28349, skipping destruction (fork without exec?)
Starting app 1113000
>>> Adding process 28347 for game ID 1113000
GameAction [AppID 1113000, ActionID 1] : LaunchApp changed task to WaitingGameWindow with ""
>>> Adding process 28348 for game ID 1113000
GameAction [AppID 1113000, ActionID 1] : LaunchApp changed task to Completed with ""
>>> Adding process 28349 for game ID 1113000
>>> Adding process 28350 for game ID 1113000
>>> Adding process 28619 for game ID 1113000
Traceback (most recent call last):
  File "/usr/lib/python3.7/tarfile.py", line 2206, in makelink
    os.symlink(tarinfo.linkname, targetpath)
OSError: [Errno 22] Invalid argument: '../drive_c' -> '/media/catgirl/Seagate HDD/SteamLibrary/steamapps/common/Proton 6.3/dist/./share/default_pfx/dosdevices/c:'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/catgirl/Seagate HDD/SteamLibrary/steamapps/common/Proton 6.3/proton", line 1253, in <module>
    g_proton.extract_tarball()
  File "/media/catgirl/Seagate HDD/SteamLibrary/steamapps/common/Proton 6.3/proton", line 318, in extract_tarball
    tar.extractall(path=self.dist_dir)
  File "/usr/lib/python3.7/tarfile.py", line 2004, in extractall
    numeric_owner=numeric_owner)
  File "/usr/lib/python3.7/tarfile.py", line 2046, in extract
    numeric_owner=numeric_owner)
  File "/usr/lib/python3.7/tarfile.py", line 2124, in _extract_member
    self.makelink(tarinfo, targetpath)
  File "/usr/lib/python3.7/tarfile.py", line 2217, in makelink
    targetpath)
  File "/usr/lib/python3.7/tarfile.py", line 2118, in _extract_member
    self.makedir(tarinfo, targetpath)
  File "/usr/lib/python3.7/tarfile.py", line 2147, in makedir
    os.mkdir(targetpath, 0o700)
OSError: [Errno 22] Invalid argument: '/media/catgirl/Seagate HDD/SteamLibrary/steamapps/common/Proton 6.3/dist/./share/default_pfx/dosdevices/c:'
Game removed: AppID 1113000 "", ProcID 28347 
Uploaded AppInterfaceStats to Steam
Exiting app 1113000
No cached sticky mapping in ActivateActionSet.
```

**Comment by kisak-valve** [comment]
Hello @irlcatgirl, we're tracking issues with Proton in the [Proton issue tracker](https://github.com/ValveSoftware/Proton/issues).

This looks like the issue being tracked at https://github.com/ValveSoftware/Proton/issues/5168. Using Proton with partitions formatted with NTFS is known to be temperamental and using a linux native filesystem instead is recommended. Closing as a duplicate.
