### ISSUE TITLE
32 bit source based games crash in bink video playback

### ISSUE THREAD

**Issue by KungFuJesus** [ValveSoftware/steam-for-linux#8260]
#### Your system information

* Steam client version (build number or date): Nov 19, 2021 (1637358733)
* Distribution (e.g. Ubuntu): Gentoo
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

The game (HL2) should launch successfully, but it crashes very early.  Setting the debugger to gdb and launching, I see the following stack trace:

```Thread 1 "hl2_linux" received signal SIGSEGV, Segmentation fault.
0xf7e21192 in __fstatat64_time64 () from /lib/libc.so.6
(gdb) bt
#0  0xf7e21192 in __fstatat64_time64 () at /lib/libc.so.6
#1  0xf7e20d5c in __fstat64_time64 () at /lib/libc.so.6
#2  0xf7df3211 in  () at /lib/libc.so.6
#3  0xf7e35b0c in get_nprocs_conf () at /lib/libc.so.6
#4  0xebf2ed29 in YUV12 () at /home/adam/.local/share/Steam/steamapps/common/Half-Life 2/bin/video_bink.so
#5  0xebf36d3c in BinkSetSoundTrack () at /home/adam/.local/share/Steam/steamapps/common/Half-Life 2/bin/video_bink.so
#6  0xebf3acb8 in BinkOpen () at /home/adam/.local/share/Steam/steamapps/common/Half-Life 2/bin/video_bink.so
#7  0xebf19bc5 in  () at /home/adam/.local/share/Steam/steamapps/common/Half-Life 2/bin/video_bink.so
#8  0xebf1a07e in  () at /home/adam/.local/share/Steam/steamapps/common/Half-Life 2/bin/video_bink.so
#9  0xebf1a5c6 in  () at /home/adam/.local/share/Steam/steamapps/common/Half-Life 2/bin/video_bink.so
#10 0xf085746e in  () at /home/adam/.local/share/Steam/steamapps/common/Half-Life 2/bin/video_services.so
#11 0xf1609540 in  () at /home/adam/.local/share/Steam/steamapps/common/Half-Life 2/bin/engine.so
#12 0xf160971a in  () at /home/adam/.local/share/Steam/steamapps/common/Half-Life 2/bin/engine.so
#13 0xf1605d7a in  () at /home/adam/.local/share/Steam/steamapps/common/Half-Life 2/bin/engine.so
#14 0xf160669d in  () at /home/adam/.local/share/Steam/steamapps/common/Half-Life 2/bin/engine.so
#15 0xf16017db in  () at /home/adam/.local/share/Steam/steamapps/common/Half-Life 2/bin/engine.so
#16 0xf1602372 in  () at /home/adam/.local/share/Steam/steamapps/common/Half-Life 2/bin/engine.so
#17 0xf63133d8 in  () at bin/launcher.so
#18 0xf63133d8 in  () at bin/launcher.so
#19 0xf62fa29e in LauncherMain () at bin/launcher.so
#20 0x08048564 in main ()
(gdb) q
```

I use glibc 2.34 and given the crash happens in libc, it seems likely this is part of the puzzle.  The function at the top of the stack doesn't quite make much sense (not entirely sure why get_nprocs_conf would call fstat, but I guess it's possible that it's opening files in procfs.  The time64 primitive variant here could be prescient, as I think that was a major change in glibc.  

#### Steps for reproducing this issue:

1. Launch the game (HL2, L4D2, any number of course based games)

At present, the workaround is just to apply -novid and it gets past the bink call.  I'm currently using HL2 beta when I see this issue.  I also see a crash when launching with -vulkan, but that's likely to be a separate issue.

**Comment by KungFuJesus** [comment]
I believe this better belongs in source-1-games' issues.  Can an admin move this issue there?  Sorry about that.
