### ISSUE TITLE
Titles do not start when launched from inside steam

### ISSUE THREAD

**Issue by mlauss** [ValveSoftware/steam-for-linux#8297]
#### Your system information

* Steam client version (build number or date):  Dec  2 2021 07:35:48
* Distribution (e.g. Ubuntu):  Gentoo 64bit
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

None of the games launched through Steam do actually launch.  The "Launch" Icon briefly goes Green, the quickly back
to gray.  No game window is ever opened or visible.  This happens to both Linux native titles, and titles played via Proton.
It only happens to titles which actively use the steam library.  I have e.g. both the Steam and GOG Versions of "Factorio",
and the GOG version runs just fine, the Steam version does not.
Running with or without Steam Runtime (STEAM_RUNTIME=0) does not help.

see attached log, there's just a fraction of a second between the last 2 printed "GameAction" lines (where it starts the
game and waits for it to terminate).
[steam-native-title-launch-log.txt](https://github.com/ValveSoftware/steam-for-linux/files/7702260/steam-native-title-launch-log.txt)

#### Steps for reproducing this issue:

1. run any title in steam linux 
2. 
3.

**Comment by mlauss** [comment]
It looks like the "reaper" process is crashing somewhere in glibc before it launches the title:
``
# gdb /home/mano/.local/share/Steam/ubuntu12_32/reaper
GNU gdb (Gentoo 9999 vanilla) 12.0.50.20211213-git
Reading symbols from /home/mano/.local/share/Steam/ubuntu12_32/reaper...
(No debugging symbols found in /home/mano/.local/share/Steam/ubuntu12_32/reaper)
(gdb) core reaper-716269-1000-100.1639397182.core 
warning: core file may not match specified executable file.
[New LWP 716269]
warning: Section `.reg-xstate/716269' in core file too small.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/home/mano/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=427520 -- /h'.
Program terminated with signal SIGSEGV, Segmentation fault.
warning: Section `.reg-xstate/716269' in core file too small.
#0  0xf7d4458f in dlvsym_implementation (dl_caller=0xf7f383d8, version=0xf7f44206 "GLIBC_2.0", name=0xf7f44210 "dlsym", handle=0xffffffff) at dlvsym.c:50
50        args.handle = handle;
(gdb) bt
#0  0xf7d4458f in dlvsym_implementation (dl_caller=0xf7f383d8, version=0xf7f44206 "GLIBC_2.0", name=0xf7f44210 "dlsym", handle=0xffffffff) at dlvsym.c:50
#1  ___dlvsym (handle=0xffffffff, name=0xf7f44210 "dlsym", version=0xf7f44206 "GLIBC_2.0") at dlvsym.c:72
#2  0xf7f383d8 in ?? () from /home/mano/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so
#3  0xf7f35305 in dlsym () from /home/mano/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so
#4  0xf78e51b2 in ?? () from /usr/lib/libGLdispatch.so.0
#5  0xf78e3174 in ?? () from /usr/lib/libGLdispatch.so.0
#6  0xf7f6e42b in call_init (env=0xffc304ec, argv=0xffc304d4, argc=5, l=<optimized out>) at dl-init.c:70
#7  call_init (l=<optimized out>, argc=5, argv=0xffc304d4, env=0xffc304ec) at dl-init.c:26
#8  0xf7f6e51a in _dl_init (main_map=<optimized out>, argc=5, argv=0xffc304d4, env=0xffc304ec) at dl-init.c:117
#9  0xf7f5e0ba in _dl_start_user () from /lib/ld-linux.so.2
``

**Comment by mlauss** [comment]
Turns out is is an issue with stack alignment when glibc is built with vectorization enabled.
Building glibc without vectorization gets everything running again.
