### ISSUE TITLE
Steam freezes after exiting CS:GO and when joining online Civilization VI room

### ISSUE THREAD

**Issue by taoky** [ValveSoftware/steam-for-linux#8893]
#### Your system information

* Steam client version (build number or date): Oct 19 2022, at 00:56:44
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Env: GNOME 43.0 Wayland

Expected:

Steam client works normally after exiting CS:GO and when joining online Civ VI room with "Join Game" in "Friends & Chat".

Actually:

Steam client freezes and eats 100% CPU (and also Civ VI freezes). With GDB attached this is the backtrace of the offending process:

```
(gdb) bt
#0  0xf7ee2549 in __kernel_vsyscall ()
#1  0xf7717336 in ?? () from /usr/lib32/libc.so.6
#2  0xf76835ed in ?? () from /usr/lib32/libc.so.6
#3  0xf7686c7c in __pthread_cond_timedwait64 () from /usr/lib32/libc.so.6
#4  0xf7686da2 in pthread_cond_timedwait () from /usr/lib32/libc.so.6
#5  0xe7b9762b in SteamThreadTools::CThreadSyncObject::Wait(unsigned int) ()
   from /home/taoky/.local/share/Steam/ubuntu12_32/libtier0_s.so
#6  0xc6e0b573 in ?? () from /home/taoky/.local/share/Steam/ubuntu12_32/steamclient.so
#7  0xc6dea4be in ?? () from /home/taoky/.local/share/Steam/ubuntu12_32/steamclient.so
#8  0xc6deab60 in ?? () from /home/taoky/.local/share/Steam/ubuntu12_32/steamclient.so
#9  0xc6dd09c2 in ?? () from /home/taoky/.local/share/Steam/ubuntu12_32/steamclient.so
#10 0xc695b50d in ?? () from /home/taoky/.local/share/Steam/ubuntu12_32/steamclient.so
#11 0xdee7746d in ?? () from /home/taoky/.local/share/Steam/ubuntu12_32/steamui.so
#12 0xde90bd72 in ?? () from /home/taoky/.local/share/Steam/ubuntu12_32/steamui.so
#13 0xde90e102 in ?? () from /home/taoky/.local/share/Steam/ubuntu12_32/steamui.so
#14 0x5663f800 in ?? ()
#15 0x56640702 in ?? ()
#16 0x5662779e in ?? ()
#17 0xf761f119 in ?? () from /usr/lib32/libc.so.6
#18 0xf761f1ed in __libc_start_main () from /usr/lib32/libc.so.6
#19 0x5662d2fd in _start ()
```

It looks like a deadlock, and I didn't find any similar issues on steam-for-linux repo.

#### Steps for reproducing this issue:

1. `pacman -S steam`
2. Download CS:GO or Sid Meier's Civilization VI
3. Run CS:GO and exits; or run civ and join a friend's game

**Comment by taoky** [comment]
The current Steam Flatpak version also freezes.

**Comment by taoky** [comment]
This bug seems to have been fixed with "Nov 17 2022, at 02:45:32" Steam client build and latest Arch Linux packages.

**Comment by taoky** [comment]
Sorry but it happens again after a reboot and with client "Dec 1 2022, at 22:40:28", so I think that I should reopen this issue...

**Comment by taoky** [comment]
Seems not reproducible now... I'll try to debug it when this happens again.
