### ISSUE TITLE
Steam beta crashes along with the game when requesting sound input

### ISSUE THREAD

**Issue by GregTheMadMonk** [ValveSoftware/steam-for-linux#9004]
#### Your system information

* Steam client version (build number or date): Dec 15 2022 02:03:59
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

The issue first appeared after an update when I tried to launch Nightmare Reaper.
The game crashed on launch, and Steam crashed with it.
At first, I thought it was a game-specific problem, as other games worked, but when I tried to use voice chat in Half-Life it happened again.
Inspecting the core dump reveals that `alcCaptureOpenDevice()` fails and crashes both the game and steam.
Full `gdb` backtrace:

```
#0  0xf7ee4549 in __kernel_vsyscall ()
#1  0xf7a89667 in ?? () from /usr/lib32/libc.so.6
#2  0xf7a35677 in raise () from /usr/lib32/libc.so.6
#3  0xf7a1e126 in abort () from /usr/lib32/libc.so.6
#4  0xedaca235 in ?? () from /home/greg/.local/share/Steam/ubuntu12_32/vgui2_s.so
#5  0xedb61c89 in __gxx_personality_v0 () from /home/greg/.local/share/Steam/ubuntu12_32/vgui2_s.so
#6  0xf416f834 in _Unwind_RaiseException_Phase2 (exc=0xd91995a0, context=0xe97fd310, frames_p=0xe97fd390) at /usr/src/debug/gcc/libgcc/unwind.inc:64
#7  0xf416fd88 in _Unwind_RaiseException (exc=<optimized out>) at /usr/src/debug/gcc/libgcc/unwind.inc:136
#8  0xee286836 in __cxxabiv1::__cxa_throw (obj=0xd91995c0, tinfo=0xeda3a7d8, dest=0xed988800) at /usr/src/debug/gcc/libstdc++-v3/libsupc++/eh_throw.cc:93
#9  0xed94a5fe in ?? () from /usr/lib32/libopenal.so.1
#10 0xed97cb85 in alcCaptureOpenDevice () from /usr/lib32/libopenal.so.1
#11 0xeb2f754e in ?? () from /home/greg/.local/share/Steam/ubuntu12_32/steamclient.so
#12 0xeb2f7609 in ?? () from /home/greg/.local/share/Steam/ubuntu12_32/steamclient.so
#13 0xeb2e63fb in ?? () from /home/greg/.local/share/Steam/ubuntu12_32/steamclient.so
#14 0xeae15544 in ?? () from /home/greg/.local/share/Steam/ubuntu12_32/steamclient.so
#15 0xeaa96113 in ?? () from /home/greg/.local/share/Steam/ubuntu12_32/steamclient.so
#16 0xeaca34e8 in ?? () from /home/greg/.local/share/Steam/ubuntu12_32/steamclient.so
#17 0xeae5067f in ?? () from /home/greg/.local/share/Steam/ubuntu12_32/steamclient.so
#18 0xeaca2f17 in ?? () from /home/greg/.local/share/Steam/ubuntu12_32/steamclient.so
#19 0xeae4d6c2 in ?? () from /home/greg/.local/share/Steam/ubuntu12_32/steamclient.so
#20 0xeae4fa85 in ?? () from /home/greg/.local/share/Steam/ubuntu12_32/steamclient.so
#21 0xeae50231 in ?? () from /home/greg/.local/share/Steam/ubuntu12_32/steamclient.so
#22 0xf2c0f19e in SteamThreadTools::CThread::ThreadExceptionWrapper(void*) () from /home/greg/.local/share/Steam/ubuntu12_32/libtier0_s.so
#23 0xf2c0ca0e in ?? () from /home/greg/.local/share/Steam/ubuntu12_32/libtier0_s.so
#24 0xf2c0d2d0 in CatchAndWriteMiniDumpExForVoidPtrFn () from /home/greg/.local/share/Steam/ubuntu12_32/libtier0_s.so
#25 0xf2c0d318 in CatchAndWriteMiniDumpForVoidPtrFn () from /home/greg/.local/share/Steam/ubuntu12_32/libtier0_s.so
#26 0xf2c11c21 in SteamThreadTools::CThread::ThreadProc(void*) () from /home/greg/.local/share/Steam/ubuntu12_32/libtier0_s.so
#27 0xf7a87485 in ?? () from /usr/lib32/libc.so.6
#28 0xf7b24efc in ?? () from /usr/lib32/libc.so.6
```

#### Steps for reproducing this issue:

1. Launch the latest Steam Beta
2. Try to run a game that uses a microphone (for me these were Nightmare Reaper and Half-Life)
3. Both game and steam would crash when trying to access the microphone

**Comment by kisak-valve** [comment]
Hello @GregTheMadMonk, I agree with @bananarne that this is the same issue as #8930. Since this issue report adds a little more detail, I've gone ahead and transferred the issue report to https://github.com/ValveSoftware/steam-for-linux/issues/8930#issuecomment-1354861728.

Closing in favor of the older issue report.
