### ISSUE TITLE
SIGBUS when opening the beta in-game overlay

### ISSUE THREAD

**Issue by Ryhon0** [ValveSoftware/steam-for-linux#9461]
#### Your system information

* Steam client version: 1683253302
* Distribution: Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Opening the in-game overlay in any way crashes the game with SIGBUS. Happens on the Flatpak version, steam and steam-native-runtime from Arch repos.

coredumpctl gives the following stack trace:
```
#0  0x00007f6ed0243772 n/a (/home/ryhon/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so + 0x27772)
```

#### Steps for reproducing this issue:

1. Opt into the client beta
2. Launch any game
3. Open the in-game overlay using the key shortcut or by opening a link in a game

**Comment by kisak-valve** [comment]
Hello @Ryhon0, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. Also, please list some games you saw this issue with.

**Comment by Ryhon0** [comment]
System information: https://gist.githubusercontent.com/Ryhon0/ecf1954fe4320e5050fba24a448df75e/raw/9f036b339787ca33b879e3eb98f4a967c0d65433/gistfile1.txt

This only happens with the native version of CS:GO for me.
x86 native version of GMod, Chronicles of Myrtana: Archolos and Aim Lab with Proton Experimental all work fine

**Comment by kisak-valve** [comment]
Thanks, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/3172. Since this issue report adds a bit more detail to ponder, I've transferred this issue report to https://github.com/ValveSoftware/csgo-osx-linux/issues/3172#issuecomment-1536398210.

**Comment by TTimo** [comment]
@Ryhon0 can you provide a crash ID for an uploaded minidump crash when you get this in CS:GO?

**Comment by flibitijibibo** [comment]
Apologies for reviving a closed thread, but I managed to reproduce this with a non-Source game with a retail Steam Deck running in desktop mode. It occurs with both OpenGL and Vulkan and seems to occur after a fixed number of frames (so you can actually put arbitrary sleeps between the frames and it still crashes at the same point).

This was the best stack I could get, Valgrind didn't like the game very much (CoreCLR woes):

```
Thread 1 "CobaltCore" received signal SIGBUS, Bus error.
0x00007f09c20f2752 in ?? () from target:/tmp/pressure-vessel-libs-QLLWC2/x86_64/gameoverlayrenderer.so
(gdb) bt
#0  0x00007f09c20f2752 in ?? () from target:/tmp/pressure-vessel-libs-QLLWC2/x86_64/gameoverlayrenderer.so
#1  0x00007f09c20e4dd5 in ?? () from target:/tmp/pressure-vessel-libs-QLLWC2/x86_64/gameoverlayrenderer.so
#2  0x00007f09c20ee994 in ?? () from target:/tmp/pressure-vessel-libs-QLLWC2/x86_64/gameoverlayrenderer.so
#3  0x00007f09c20ef152 in ?? () from target:/tmp/pressure-vessel-libs-QLLWC2/x86_64/gameoverlayrenderer.so
#4  0x00007f09c20f0a6b in ?? () from target:/tmp/pressure-vessel-libs-QLLWC2/x86_64/gameoverlayrenderer.so
#5  0x00007f09c20e1115 in glXSwapBuffers () from target:/tmp/pressure-vessel-libs-QLLWC2/x86_64/gameoverlayrenderer.so
#6  0x00007ec908e3ffc3 in ?? () from target:/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#7  0x00007ec8fc218ec8 in OPENGL_SwapBuffers () from target:/run/media/mmcblk0p1/steamapps/common/Cobalt Core/netcoredeps/libFNA3D.so.0
#8  0x0000560d8db0d102 in ?? ()
```

The most common case is it crashing on the first frame where the overlay would have drawn its first popup; one other behavior I haven't reproduced is the overlay pop-up being solid white, and attempting to start the overlay resulted in an exit, Steam didn't have any logs for it AFAICT.

**Comment by TTimo** [comment]
@flibitijibibo please consider opening a separate report (that being said, we are aware of various crashes and incompatibilities with the overlay already, those are being worked on).

**Comment by flibitijibibo** [comment]
Spun a new issue: #10164
