### ISSUE TITLE
Steam Big Picture Crashing while loading user data when launching

### ISSUE THREAD

**Issue by lvlanson** [ValveSoftware/steam-for-linux#9469]
#### Your system information

* Steam client version (build number or date): 1.0.0.75-3
* Distribution (e.g. Ubuntu):  Kernel: 6.1.25-1-MANJARO (FULLY UPDATED)
* Opted into Steam client beta?: YES
* Have you checked for system updates?: YES

#### Please describe your issue in as much detail as possible:
Big Picture is crashing when loading. It is crashing at the point where it loads user data. In terminal I receive a segmentation fault. Upon request I can share the dump file. Standard steam and old big picture mode is still working as expected.

#### Steps for reproducing this issue:

STEPS
Start Steam in Big Picture mode (Thats it)

RESULTS
I am at the desktop again, the application crashed

EXPECTED
The application launches

ADDITIONAL INFORMATION
I have this issue now for like 2 months. I could always start steam from the terminal in old bigpicture mode. Since I heard that the new beta had improvements I was eager to try it. Since I activated it will always open in new bigpicture mode and will crash as described above. Is there any way to launch steam in desktop mode? I can't open steam at all this way.

**Comment by blazingtime** [comment]
Having the same issue here.

I'm on Debian Bookworm. I have configured steam to launch in big picture mode, with asking which account to use. The issue seems to be hardware issue and distro-independent, as the problem persists on Debian Sid and Ubuntu 23.10, and @lvlanson  is on Manjaro.
After selecting any of two, steam starts loading user data, then crashes to desktop.

Running `DEBUGGER=gdb steam` and backtracing when the crach accurs turns back:
`
Thread 1 "steam" received signal SIGSEGV, Segmentation fault.
0xf7894158 in ?? () from /lib/i386-linux-gnu/libGLX_mesa.so.0
(gdb) backtrace
#0  0xf7894158 in ?? () from /lib/i386-linux-gnu/libGLX_mesa.so.0
#1  0xf78de896 in ?? () from /lib/i386-linux-gnu/libGLX.so.0
#2  0xf78df210 in ?? () from /lib/i386-linux-gnu/libGLX.so.0
#3  0xf78e03f4 in ?? () from /lib/i386-linux-gnu/libGLX.so.0
#4  0xe3e9d47c in ?? () from /home/bt/.steam/debian-installation/ubuntu12_32/vgui2_s.so
#5  0xe3e9d800 in ?? () from /home/bt/.steam/debian-installation/ubuntu12_32/vgui2_s.so
#6  0xe3e562ce in ?? () from /home/bt/.steam/debian-installation/ubuntu12_32/vgui2_s.so
#7  0xe3e77fcc in ?? () from /home/bt/.steam/debian-installation/ubuntu12_32/vgui2_s.so
#8  0xe3e72a83 in ?? () from /home/bt/.steam/debian-installation/ubuntu12_32/vgui2_s.so
#9  0xe6425949 in ?? () from /home/bt/.steam/debian-installation/ubuntu12_32/steamui.so
#10 0xe69011dc in ?? () from /home/bt/.steam/debian-installation/ubuntu12_32/steamui.so
#11 0xe64a5342 in ?? () from /home/bt/.steam/debian-installation/ubuntu12_32/steamui.so
#12 0xe641299f in ?? () from /home/bt/.steam/debian-installation/ubuntu12_32/steamui.so
#13 0xe641450f in ?? () from /home/bt/.steam/debian-installation/ubuntu12_32/steamui.so
#14 0x5659fbe9 in RunSteam(int, char**, bool) ()
#15 0x565a0afe in ?? ()
#16 0x5658abb0 in main ()
`

OR

`
Thread 1 "steam" received signal SIGSEGV, Segmentation fault.
0xf7ab5ea1 in ?? () from /lib/i386-linux-gnu/libc.so.6
(gdb) backtrace
#0  0xf7ab5ea1 in ?? () from /lib/i386-linux-gnu/libc.so.6
#1  0x00000000 in ?? ()
`

I have a thinkpad x220i, and looks like it's iGPU does not support Vulkan. That might be the issue, since it looks like big picture requires something Vulkan'ish during loading user data. @lvlanson please confirm that your GPU supports Vulkan and you have installed appropriate Vulkan drivers.

The issue seems unreproducable when entering big picture from an already logged in account on "common" steam ui, and big picture starts successfully.  

It seems not to be possible to exit big picture mode without logging in to steam, so the app is completely broken for me. It seems big picture mode is enabled in steam biniries themselves, not configs.

Temporary solution for me: 

1. completely uninstall steam from system
2. delete `~/.steam`
3. install steam again
4. do not enter big picture mode on this hardware. 

Steam should at least ensure to have a way to exit big picture before logging in.

**Comment by christag** [comment]
I'm having this same problem as described above - Debian Bookworm on MacMini5,1. Big picture itself works fine if launched from Steam while running but when trying to login or switch users it crashes
