### ISSUE TITLE
Ubuntu 22.04 64-bit SegFault

### ISSUE THREAD

**Issue by madrang** [ValveSoftware/steam-for-linux#9991]
#### System information
* Steam client version (build number or date): updater built Aug 12 2023 04:39:46
* Distribution (e.g. Ubuntu): Ubuntu 22.04 64-bit
* Opted into Steam client beta?: [Yes/No] Issue with Both, Currently on Beta
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12352213/steam-logs.tar.gz)
* GPU: NVIDIA GeForce GTX TITAN X

#### Please describe your issue in as much detail as possible:
Either Steam will crash while opening the UI or will open but refuse to download any game updates.
Clicking Play also does nothing.
```
TagLib: ID3v2.4 no longer supports the frame type TDAT.  It will be discarded from the tag.
BuildCompleteAppOverviewChange: 3148 apps
RegisterForAppOverview 1: 368ms
RegisterForAppOverview 2: 372ms
src/tier1/utlmemory.cpp (317) : num >= 0
assert_20230815024200_46.dmp[7410]: Uploading dump (out-of-process)
/tmp/dumps/assert_20230815024200_46.dmp
double free or corruption (out)
assert_20230815024200_46.dmp[7410]: Finished uploading minidump (out-of-process): success = yes
assert_20230815024200_46.dmp[7410]: response: CrashID=bp-8ac4a5ad-677a-4997-94cd-0dc3f2230814
assert_20230815024200_46.dmp[7410]: file ''/tmp/dumps/assert_20230815024200_46.dmp'', upload yes: ''CrashID=bp-8ac4a5ad-677a-4997-94cd-0dc3f2230814''
malloc(): invalid size (unsorted)


src/tier0/threadtools.cpp (4197) : Probably deadlock or failure waiting for thread to initialize.
[2023-08-15 02:43:51] Background update loop checking for update. . .
[2023-08-15 02:43:51] Checking for available updates...
[2023-08-15 02:43:51] Downloading manifest: https://client-update.akamai.steamstatic.com/steam_client_publicbeta_ubuntu12
```

#### Steps for reproducing this issue:

1. Boot system
2. Start Steam
3. SegFault

**Comment by madrang** [comment]
Tried submitting a HelpRequest HT-CCJJ-Q288-92VT
```
We've been unable to reproduce these issues here and we're not receiving a widespread report of this from other users.

Because of the number of potential causes, we can also only recommend working with someone who has local access to your PC for help with general troubleshooting. Because there are multiple games were affected, this indicates larger issues occurring on your machine that we can't help with remotely.

In the meantime, I would encourage you to search for this issue and keep using the Steam community hubs and Github links we provided, it's possible other users have experienced similar issues and can offer helpful advice.

I’m sorry we can’t be of more help with this particular issue but.

Because we have provided all the information we have for your issue I'm closing this help request. If you have an unrelated issue please open a new help request and we will be happy to help.

Steam Support
```
It seems GitHub is my only hope of using Steam again...

**Comment by madrang** [comment]
Updating my Kernel from 5.15.0.83.80 to 6.2.0.26.26~22.04.7 seems to have fixed it.
I guess the last kernel update broke Steam and I didn't notice until after a little while.
Hopefully this issue doesn't come back.

**Comment by madrang** [comment]
Less frequent after the update but still happens after a while.
```
src/tier1/utlmemory.cpp (317) : num >= 0
assert_20230816202614_1877.dmp[365852]: Uploading dump (out-of-process)
/tmp/dumps/assert_20230816202614_1877.dmp
crash_20230816202614_1878.dmp[365855]: Uploading dump (out-of-process)
/tmp/dumps/crash_20230816202614_1878.dmp
/home/madrang/.steam/steam.sh: line 798: 11817 Segmentation fault      (core dumped) "$STEAMROOT/$STEAMEXEPATH" "$@"
(base) madrang@ASTitan:~$ assert_20230816202614_1877.dmp[365852]: Finished uploading minidump (out-of-process): success = yes
assert_20230816202614_1877.dmp[365852]: response: CrashID=bp-f27e89c8-4c82-41ef-a5d7-4d6ac2230816
assert_20230816202614_1877.dmp[365852]: file ''/tmp/dumps/assert_20230816202614_1877.dmp'', upload yes: ''CrashID=bp-f27e89c8-4c82-41ef-a5d7-4d6ac2230816''
crash_20230816202614_1878.dmp[365855]: Finished uploading minidump (out-of-process): success = yes
crash_20230816202614_1878.dmp[365855]: response: CrashID=bp-7c61ff4b-7b3b-446d-b946-98a242230816
crash_20230816202614_1878.dmp[365855]: file ''/tmp/dumps/crash_20230816202614_1878.dmp'', upload yes: ''CrashID=bp-7c61ff4b-7b3b-446d-b946-98a242230816''
```

**Comment by madrang** [comment]
![image](https://github.com/ValveSoftware/steam-for-linux/assets/747243/46a36c90-b439-46a5-8449-8ceea281d973)
![image](https://github.com/ValveSoftware/steam-for-linux/assets/747243/81c4741e-4842-41c0-b963-83d5bbdbac67)

**Comment by kisak-valve** [comment]
Hello @madrang, what version of the NVIDIA driver are you using?

**Comment by pikachurus** [comment]
same (Ubuntu 22.04, Kernel 6.2.0.26 and 5.19.0.50, Steam 1690583737, Nvidia Driver 530.30 and 535.98):

Aug 22 20:12:37 PC kernel: [ 58.297874] vulkandriverque[5597]: segfault at 7f296170702d ip 00007f296170702d sp 00007fffe55bd428 error 14 in libvulkan_nouveau.so[7fc91f000000+65000] likely on CPU 11 (core 6, socket 0)
Aug 22 20:13:39 PC whoopsie-upload-all[5962]: INFO:root:/var/crash/_usr_bin_vulkaninfo.0.crash already marked for upload, skipping

**Comment by kisak-valve** [comment]
Hello @pikachurus, `libvulkan_nouveau.so` This is mesa/NVK, which is brand new and not in any not in any mesa point release yet.

I would test temporarily disable that vulkan driver in `/usr/share/vulkan/icd.d/` by renaming it to anything that doesn't end in `.json` (like `.json.disabled`) and see if that has a significant effect. If it does, then report the issue to the mesa/NVK dev(s).

**Comment by madrang** [comment]
> Hello @madrang, what version of the NVIDIA driver are you using?

@kisak-valve I just recently updated to 535.86.10 and still have the same issue.
Thanks for looking into this.

**Comment by madrang** [comment]
About half the time I get the crash, but the UI remains usable. Only it won't download updates...
So I made a GIF of the UI in the odd crashed state.
![Peek 2023-08-24 22-56](https://github.com/ValveSoftware/steam-for-linux/assets/747243/7ede3470-1e57-4a3b-bc86-e3c18e35299b)

**Comment by pikachurus** [comment]
> Hello @pikachurus, `libvulkan_nouveau.so` This is mesa/NVK, which is brand new and not in any not in any mesa point release yet.
> 
> I would test temporarily disabling that vulkan driver in `/usr/share/vulkan/icd.d/` by renaming it to anything that doesn't end in `.json` (like `.json.disabled`) and see if that has a significant effect. If it does, then report the issue to the mesa/NVK dev(s).

Thanks for reply, but it won't help.

But i replaced /usr/lib/x86_64-linux-gnu/libvulkan_lvp.so with older file (from previous desktop's backup (13 august)), and games starting again.

**Comment by madrang** [comment]
I decided to run it in a loop tonight, so if it crashes it just starts again.
```
while [ true ]; do steam; done
```
Getting the same crash as before.
```
src/tier1/utlmemory.cpp (317) : num >= 0
src/tier1/utlmemory.cpp (317) : num >= 0
assert_20230830015656_45.dmp[4094518]: Uploading dump (out-of-process)
/tmp/dumps/assert_20230830015656_45.dmp
invalid fastbin entry (free)
double free or corruption (out)
assert_20230830015656_45.dmp[4094518]: Finished uploading minidump (out-of-process): success = yes
assert_20230830015656_45.dmp[4094518]: response: CrashID=bp-0c4ebc47-dff2-4936-914d-c66462230829
assert_20230830015656_45.dmp[4094518]: file ''/tmp/dumps/assert_20230830015656_45.dmp'', upload yes: ''CrashID=bp-0c4ebc47-dff2-4936-914d-c66462230829''
```
Except that tonight i decided to just leave it running generating many CrashIDs
```
bp-9640da61-01e8-4433-a9a9-366132230829
bp-8a64a64f-8cab-47fa-8dd8-c247c2230829
bp-6f766e78-b155-400b-be8a-7379e2230829
bp-2c9b7a7c-cc18-4343-a664-1f5012230829
bp-bdaff6b3-7b84-48c5-a888-6e0212230829
bp-7da3a257-9098-4b23-8554-64d5b2230829
bp-db37efee-794d-4285-b63c-604892230829
bp-1e0dfe7d-9c93-4a52-9fa9-cdcb92230829
bp-5ad02547-ff65-46a7-ae1d-84b9e2230829
bp-04976c50-6830-4719-8202-4e7082230829
bp-66368969-f8ec-4baf-9f0b-7b7ef2230829
bp-e15ac5c9-864c-4504-bb0f-3b5752230829
bp-5ca1a174-04ac-49e8-a66a-3a69b2230829
bp-b3036859-122c-4729-96cd-b8e512230829
bp-3ca78d9c-6ce6-4e64-acbf-74c472230829
```
All the minidumps seems to upload just fine. So hopefully one of those could help figure out the issue.

**Comment by madrang** [comment]
Trying again once in a while to figure this out....
```
Steam logging initialized: directory: /home/madrang/.steam/logs

XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xf08059c0
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xf08041f0
steamwebhelper.sh[516527]: Runtime for steamwebhelper: defaulting to /home/madrang/.steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[516527]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
Steam Runtime Launch Service: starting steam-runtime-launcher-service
Steam Runtime Launch Service: steam-runtime-launcher-service is running pid 516649
bus_name=com.steampowered.PressureVessel.LaunchAlongsideSteam
CAppInfoCacheReadFromDiskThread took 709 milliseconds to initialize
Fossilize INFO: Setting autogroup scheduling.
BRefreshApplicationsInLibrary 1: 8ms
src/tier1/utlmemory.cpp (317) : num >= 0
src/tier1/utlmemory.cpp (317) : num >= 0
assert_20230906225638_39.dmp[522142]: Uploading dump (out-of-process)
/tmp/dumps/assert_20230906225638_39.dmp
crash_20230906225639_40.dmp[522357]: Uploading dump (out-of-process)
/tmp/dumps/crash_20230906225639_40.dmp
crash_20230906225639_41.dmp[523243]: Uploading dump (out-of-process)
/tmp/dumps/crash_20230906225639_41.dmp
crash_20230906225639_42.dmp[523249]: Uploading dump (out-of-process)
/tmp/dumps/crash_20230906225639_42.dmp
crash_20230906225639_43.dmp[523252]: Uploading dump (out-of-process)
/tmp/dumps/crash_20230906225639_43.dmp
crash_20230906225640_44.dmp[523255]: Uploading dump (out-of-process)
/tmp/dumps/crash_20230906225640_44.dmp
crash_20230906225640_45.dmp[523258]: Uploading dump (out-of-process)
/tmp/dumps/crash_20230906225640_45.dmp
assert_20230906225638_39.dmp[522142]: Finished uploading minidump (out-of-process): success = yes
assert_20230906225638_39.dmp[522142]: response: CrashID=bp-1156852c-a8cf-4ebc-bad7-ec8862230906
assert_20230906225638_39.dmp[522142]: file ''/tmp/dumps/assert_20230906225638_39.dmp'', upload yes: ''CrashID=bp-1156852c-a8cf-4ebc-bad7-ec8862230906''
crash_20230906225640_46.dmp[523261]: Uploading dump (out-of-process)
/tmp/dumps/crash_20230906225640_46.dmp
crash_20230906225640_47.dmp[523264]: Uploading dump (out-of-process)
/tmp/dumps/crash_20230906225640_47.dmp
crash_20230906225640_48.dmp[523278]: Uploading dump (out-of-process)
/tmp/dumps/crash_20230906225640_48.dmp
crash_20230906225641_49.dmp[523287]: Uploading dump (out-of-process)
/tmp/dumps/crash_20230906225641_49.dmp
crash_20230906225639_41.dmp[523243]: Finished uploading minidump (out-of-process): success = yes
crash_20230906225639_41.dmp[523243]: response: CrashID=bp-b96f92df-0991-47ae-ba82-dfe562230906
crash_20230906225639_41.dmp[523243]: file ''/tmp/dumps/crash_20230906225639_41.dmp'', upload yes: ''CrashID=bp-b96f92df-0991-47ae-ba82-dfe562230906''
crash_20230906225641_50.dmp[523290]: Uploading dump (out-of-process)
/tmp/dumps/crash_20230906225641_50.dmp
crash_20230906225641_51.dmp[523316]: Uploading dump (out-of-process)
/tmp/dumps/crash_20230906225641_51.dmp
crash_20230906225639_43.dmp[523252]: Finished uploading minidump (out-of-process): success = yes
crash_20230906225639_43.dmp[523252]: response: CrashID=bp-532c1fc6-58c2-4ab5-a772-8cd122230906
crash_20230906225639_43.dmp[523252]: file ''/tmp/dumps/crash_20230906225639_43.dmp'', upload yes: ''CrashID=bp-532c1fc6-58c2-4ab5-a772-8cd122230906''
/home/madrang/.steam/steam.sh: line 798: 516462 Segmentation fault      (core dumped) "$STEAMROOT/$STEAMEXEPATH" "$@"
(base) madrang@ASTitan:~$ crash_20230906225640_44.dmp[523255]: Finished uploading minidump (out-of-process): success = yes
crash_20230906225640_44.dmp[523255]: response: CrashID=bp-9de7931a-974e-4569-b360-a305f2230906
crash_20230906225640_44.dmp[523255]: file ''/tmp/dumps/crash_20230906225640_44.dmp'', upload yes: ''CrashID=bp-9de7931a-974e-4569-b360-a305f2230906''
crash_20230906225641_49.dmp[523287]: Finished uploading minidump (out-of-process): success = yes
crash_20230906225641_49.dmp[523287]: response: CrashID=bp-7464eb42-6b45-4c35-a78f-9427c2230906
crash_20230906225641_49.dmp[523287]: file ''/tmp/dumps/crash_20230906225641_49.dmp'', upload yes: ''CrashID=bp-7464eb42-6b45-4c35-a78f-9427c2230906''
crash_20230906225641_51.dmp[523316]: Finished uploading minidump (out-of-process): success = yes
crash_20230906225641_51.dmp[523316]: response: CrashID=bp-0216df1f-142a-4ad0-add7-ea42e2230906
crash_20230906225641_51.dmp[523316]: file ''/tmp/dumps/crash_20230906225641_51.dmp'', upload yes: ''CrashID=bp-0216df1f-142a-4ad0-add7-ea42e2230906''
crash_20230906225640_45.dmp[523258]: Finished uploading minidump (out-of-process): success = yes
crash_20230906225640_45.dmp[523258]: response: CrashID=bp-c98177dd-62c9-4101-b0d3-3711e2230906
crash_20230906225640_45.dmp[523258]: file ''/tmp/dumps/crash_20230906225640_45.dmp'', upload yes: ''CrashID=bp-c98177dd-62c9-4101-b0d3-3711e2230906''
crash_20230906225641_50.dmp[523290]: Finished uploading minidump (out-of-process): success = yes
crash_20230906225641_50.dmp[523290]: response: CrashID=bp-cddc80f7-c2ce-40dd-a66e-d071c2230906
crash_20230906225641_50.dmp[523290]: file ''/tmp/dumps/crash_20230906225641_50.dmp'', upload yes: ''CrashID=bp-cddc80f7-c2ce-40dd-a66e-d071c2230906''
crash_20230906225639_42.dmp[523249]: Finished uploading minidump (out-of-process): success = yes
crash_20230906225639_42.dmp[523249]: response: CrashID=bp-4dad7fab-1838-4a49-b2b5-833312230906
crash_20230906225639_42.dmp[523249]: file ''/tmp/dumps/crash_20230906225639_42.dmp'', upload yes: ''CrashID=bp-4dad7fab-1838-4a49-b2b5-833312230906''
crash_20230906225640_48.dmp[523278]: Finished uploading minidump (out-of-process): success = yes
crash_20230906225640_48.dmp[523278]: response: CrashID=bp-5b6819fa-5e02-4460-9dba-0471c2230906
crash_20230906225640_48.dmp[523278]: file ''/tmp/dumps/crash_20230906225640_48.dmp'', upload yes: ''CrashID=bp-5b6819fa-5e02-4460-9dba-0471c2230906''
crash_20230906225640_46.dmp[523261]: Finished uploading minidump (out-of-process): success = yes
crash_20230906225640_46.dmp[523261]: response: CrashID=bp-93d6fe26-e33e-4275-b57f-9bcfc2230906
crash_20230906225640_46.dmp[523261]: file ''/tmp/dumps/crash_20230906225640_46.dmp'', upload yes: ''CrashID=bp-93d6fe26-e33e-4275-b57f-9bcfc2230906''
crash_20230906225639_40.dmp[522357]: Finished uploading minidump (out-of-process): success = yes
crash_20230906225639_40.dmp[522357]: response: CrashID=bp-1523b3d2-7519-4cf2-ac10-073082230906
crash_20230906225639_40.dmp[522357]: file ''/tmp/dumps/crash_20230906225639_40.dmp'', upload yes: ''CrashID=bp-1523b3d2-7519-4cf2-ac10-073082230906''
crash_20230906225640_47.dmp[523264]: Finished uploading minidump (out-of-process): success = yes
crash_20230906225640_47.dmp[523264]: response: CrashID=bp-394bb43a-23e8-4ded-825a-0edd72230906
crash_20230906225640_47.dmp[523264]: file ''/tmp/dumps/crash_20230906225640_47.dmp'', upload yes: ''CrashID=bp-394bb43a-23e8-4ded-825a-0edd72230906''
```

**Comment by madrang** [comment]
Feels like it could be longer then when I bought an HTC Vive....
And 5 years later I still haven't been able to use it once.
https://github.com/ValveSoftware/SteamVR-for-Linux/issues/5
This is my experience with Valve/Steam support.
Spend thousand yet never been able to get help fix the issue.

**Comment by madrang** [comment]
Today I was really tired of that issue, so I just deleted a bunch of random folders in `~/.steam/` and forced Ubuntu to reinstall a bunch of packages randomly trying to get lucky.... Then when I restarted Steam, it started normally and started to download my game updates again.

Steam still crashes, but I noticed that tonight it was only when applying big game updates with a small download size.
At the update step all is fine usually.
![image](https://github.com/ValveSoftware/steam-for-linux/assets/747243/7c49b6c0-a4d7-4538-9937-944c7f3e313d)
Then after the download is completed and it starts `patching` that's when Steam will SegFault
![image](https://github.com/ValveSoftware/steam-for-linux/assets/747243/8272c8b3-749b-4161-ad3c-4cc7d3b1a5d8)

But tonight instead of getting stuck in a crash loop, when I restart Steam after a crash it will do a Validate step and then will redownload the whole game instead of trying to patch the content.
![image](https://github.com/ValveSoftware/steam-for-linux/assets/747243/4ec7af85-ad67-40d4-9df4-e529ca3dc862)

Steam already redownloaded more than 100GB of content tonight. But at least it's usable even if I still have to restart it once in a while.

I also did a quick Memtest and didn't find any issues.
But since every single crash starts with `src/tier1/utlmemory.cpp (317) : num >= 0` and a few invalid pointer and/or invalid chunk size error messages after it. I'm starting to think that sometimes Steam ask for too much memory when patching big games and gets a null ptr with size 0 due to the invalid request and will crash trying to use that buffer.

Not sure how to test/confirm this theory, but at least using `while [ true ]; do steam; done` makes sure Steam will open right away after crashing.

```
src/tier1/utlmemory.cpp (317) : num >= 0
src/tier1/utlmemory.cpp (317) : num >= 0
assert_20230910231719_1222.dmp[761964]: Uploading dump (out-of-process)
/tmp/dumps/assert_20230910231719_1222.dmp
realloc(): invalid pointer
malloc_consolidate(): invalid chunk size
crash_20230910231720_1223.dmp[761974]: Uploading dump (out-of-process)
```
```
src/tier1/utlmemory.cpp (317) : num >= 0
src/tier1/utlmemory.cpp (317) : num >= 0
assert_20230911010844_406.dmp[1838730]: Uploading dump (out-of-process)
/tmp/dumps/assert_20230911010844_406.dmp
malloc_consolidate(): invalid chunk size
crash_20230911010844_407.dmp[1838733]: Uploading dump (out-of-process)
/tmp/dumps/crash_20230911010844_407.dmp
/home/madrang/.steam/steam.sh: line 798: 1480025 Segmentation fault      (core dumped) "$STEAMROOT/$STEAMEXEPATH" "$@"
```
```
src/tier1/utlmemory.cpp (317) : num >= 0
src/tier1/utlmemory.cpp (317) : num >= 0
assert_20230911003757_314.dmp[1478507]: Uploading dump (out-of-process)
/tmp/dumps/assert_20230911003757_314.dmp
corrupted double-linked list
steam: ../nptl/pthread_mutex_lock.c:438: __pthread_mutex_cond_lock_full: Assertion `e != ESRCH || !robust' failed.
crash_20230911003758_315.dmp[1478510]: Uploading dump (out-of-process)
/tmp/dumps/crash_20230911003758_315.dmp
/home/madrang/.steam/steam.sh: line 798: 1388671 Segmentation fault      (core dumped) "$STEAMROOT/$STEAMEXEPATH" "$@"
```
```
src/tier1/utlmemory.cpp (317) : num >= 0
src/tier1/utlmemory.cpp (317) : num >= 0
assert_20230911002742_774.dmp[1388029]: Uploading dump (out-of-process)
/tmp/dumps/assert_20230911002742_774.dmp
crash_20230911002743_775.dmp[1388032]: Uploading dump (out-of-process)
/tmp/dumps/crash_20230911002743_775.dmp
/home/madrang/.steam/steam.sh: line 798: 1091647 Segmentation fault      (core dumped) "$STEAMROOT/$STEAMEXEPATH" "$@"
(base) madrang@ASTitan:~$ assert_20230911002742_774.dmp[1388029]: Finished uploading minidump (out-of-process): success = yes
assert_20230911002742_774.dmp[1388029]: response: CrashID=bp-6b5ba153-5ac4-4e1e-be34-218712230910
assert_20230911002742_774.dmp[1388029]: file ''/tmp/dumps/assert_20230911002742_774.dmp'', upload yes: ''CrashID=bp-6b5ba153-5ac4-4e1e-be34-218712230910''
crash_20230911002743_775.dmp[1388032]: Finished uploading minidump (out-of-process): success = yes
crash_20230911002743_775.dmp[1388032]: response: CrashID=bp-42672f43-51a1-4a9a-9a31-f8cfe2230910
crash_20230911002743_775.dmp[1388032]: file ''/tmp/dumps/crash_20230911002743_775.dmp'', upload yes: ''CrashID=bp-42672f43-51a1-4a9a-9a31-f8cfe2230910''
```

**Comment by madrang** [comment]
There are some small games that will crash Steam every single time they try to update too. Not only big patches....
I have way too many games to complete all the downloads tonight.
But for now, for those games that fails everytime it tries to update, I just pause them so they don't try to update.

**Comment by madrang** [comment]
Reinstalled most packages by now...
Trying with GDB
```
Thread 31 "CJobMgr::m_Work" received signal SIGTRAP, Trace/breakpoint trap.
[Switching to Thread 0xe35fab40 (LWP 777412)]
0xe6b3aa6b in ?? () from /home/madrang/.steam/ubuntu12_32/steamclient.so
(gdb) backtrace
#0  0xe6b3aa6b in ?? () from /home/madrang/.steam/ubuntu12_32/steamclient.so
#1  0xe6b361d2 in ?? () from /home/madrang/.steam/ubuntu12_32/steamclient.so
#2  0xe64de1c6 in ?? () from /home/madrang/.steam/ubuntu12_32/steamclient.so
#3  0xe64e0538 in ?? () from /home/madrang/.steam/ubuntu12_32/steamclient.so
#4  0xe62b8cb8 in ?? () from /home/madrang/.steam/ubuntu12_32/steamclient.so
#5  0xe7058d89 in ?? () from /home/madrang/.steam/ubuntu12_32/steamclient.so
#6  0xef83565e in SteamThreadTools::CThread::ThreadExceptionWrapper(void*) ()
   from /home/madrang/.steam/ubuntu12_32/libtier0_s.so
#7  0xef832efe in ?? () from /home/madrang/.steam/ubuntu12_32/libtier0_s.so
#8  0xef8337c0 in CatchAndWriteMiniDumpExForVoidPtrFn ()
   from /home/madrang/.steam/ubuntu12_32/libtier0_s.so
#9  0xef833808 in CatchAndWriteMiniDumpForVoidPtrFn ()
   from /home/madrang/.steam/ubuntu12_32/libtier0_s.so
#10 0xef8381b2 in SteamThreadTools::CThread::ThreadProc(void*) ()
   from /home/madrang/.steam/ubuntu12_32/libtier0_s.so
#11 0xf7a8697d in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:444
#12 0xf7b23fec in clone3 () at ../sysdeps/unix/sysv/linux/i386/clone3.S:111
(gdb) exit
A debugging session is active.
```
